apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAsJ/Z613j8b8M4EuWuYZmsaZ/AAxS4F6w2ZDc3Lb8KsXDupNQk5oCS1N2MrIuBwfkoonVC7PYuBEOffoAPNijuPopTJbmytbtAJu66+C17aUhCuFFbO7+nVpAE1MKnyJv1TL4pqkkf9DMl1IVl/AG4wiKrqB/POb95R3jSJEC8v5ziZyBbnSNu6OU9k4AiaAoFLIgrY6dA8+zrYYutkwQ7ZDldehYrxf82SaHieHGaaq326mXROM7NaLLZDv8v2rIddM8ZGt88vOorUEn9ajphoPUmW+c5WK9OdTtYaJ3DgDDwz3tNpcJzHpsvb81FvN608qNDA3E0DKJ81WEBMURU4FYDR2u6WJWsGiAWOc6XfzwG8nhIrOY19D5X9l97e/yePosrjjx2i1iXrex8iC5AZwFk0TsqCwO1l0i+gm5Vyfa6ce/uXRIrvTYu7xKncxxhFkb55gfXrPTktKw7XoPkiuGB0RTSwKrsq3IO6+uB9/hBsyNCloOXR8cHWw7AK/2Fl7FI8Pog6nZOI3rxzif7LneeOtyBiQ4+5+mkwdwQ18EJX6pHvLq9PyZ78j9sbqU+UfgYKD7s+8bvdupxynRaYyp/rL2BfdjHzy4xw0Vk47nJi2SWMePyFEv5y2EmVBYDUsNI6q/TEXF909hP0wCZJ4vxUn6H9Z9rgoCt2d8MSvhHk/UNa3NzFSJO5u8WAufjowtJyiNYqthY59W54VVsZ0vp2A2q+McL9Dm4W1lZAY8EdbKY2bz3d2sYx0C+k8dy4la2cw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
