apiVersion: v2
name: monitoring-umbrella
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 84.0.1
    repository: oci://ghcr.io/prometheus-community/charts

  - name: loki
    version: 13.2.0
    repository: oci://ghcr.io/grafana-community/helm-charts

  - name: grafana-operator
    version: 5.22.2
    repository: oci://ghcr.io/grafana/helm-charts

  - name: alloy
    version: 1.8.0
    repository: https://grafana.github.io/helm-charts
