apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-primary-pvc-labeler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cnpg-primary-pvc-labeler
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/cnpg-primary-pvc-labeler
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
