apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  destination:
    namespace: democratic-csi
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/democratic-csi
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
