apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: immich
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/immich
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  ignoreDifferences:
    # Managed by HPA
    - group: apps
      kind: Deployment
      name: immich-machine-learning
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
