apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  destination:
    namespace: inteldeviceplugins-system
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/intel-device-plugins-operator
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: restricted
        # needs hostPath volumes
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
