forgejo:
  podSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  #   readOnlyRootFilesystem: true

  httproute:
    enabled: true

    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: tailscale-int
        namespace: tailscale

    hostnames:
      - git.int.bakseter.net
