forgejo:
  podSecurityContext:
    # user 'git' has uid/gid 1000
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  #   readOnlyRootFilesystem: true

  httpRoute:
    enabled: true

    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: tailscale-int
        namespace: tailscale

    hostnames:
      - git.int.bakseter.net

  tcpRoute:
    enabled: true

    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: tailscale-int
        namespace: tailscale
        sectionName: ssh

  gitea:
    config:
      service:
        REQUIRE_SIGNIN_VIEW: false

      oauth2_client:
        ENABLE_AUTO_REGISTRATION: true

    oauth:
      - name: 'Authentik'
        provider: 'openidConnect'
        existingSecret: forgejo-oauth-secret
        autoDiscoverUrl: 'https://authentik.bakseter.no/application/o/forgejo/.well-known/openid-configuration'
        iconUrl: 'https://authentik.bakseter.no/static/dist/assets/icons/icon.png'
        scopes: 'email profile'
