apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 150Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-4fc35202-89d4-4dbb-ab11-96ee4697a943 # ref jellyfin-media
