apiVersion: v1
kind: Service
metadata:
  name: seerr-lan
  namespace: media
  labels:
    app.kubernetes.io/instance: seerr
    app.kubernetes.io/name: seerr
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: seerr
    app.kubernetes.io/name: seerr
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
