apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes
    version: v2.35.0
    releaseName: pihole
    valuesFile: values.yaml

resources:
  - pihole-admin-secret.yaml

patches:
  - target:
      kind: Deployment
      name: pihole
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
          supplementalGroups:
            - 65534

      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilites:
            drop:
              - ALL
