---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgAyvJA/hcBfAFqmmYpt4gVqukMJ2KhDKitnL/s/gOJ1TOWt3wCGl7mcQfBuHpGaqvMdAgY4SAKUobJwRWfdVh0u8KPfP71JhjctGaYYXJCM/TNYOp2RuAlly13b6yiiWFM21E3glDC4NQu2X04pDKNHrtpVA1vu1Vgw16DvIJH5xA/glRxSbho4oF9kT4Ry4oCKSD0DFEDvvhd21T92vGV8FhRrG+5gLRgC2poEHUoNXIb3azwPCcJOmP6cd3uNkRYztBBAyxAdwIGrXSgjdOSXOm9gNtASMYg/1jPou/Th5rh0ZMbs/dSETPAAV8n7ENHv7PT+njCRNNz9b7RKn264CjSGrLfhKMiTQ7glUvDpCgM+0b80q0y2t0LJhauXU1mLs3fi4dHTgavFby4U7VKBPtxzUNVFqzGjhBtgDiebftjwlnvFA60WDobFq8jPyJHaFugx/L5nyqOEPrn75VWKp6O2/iB5UOAtuhvOppfurgp6JUZNIjFrdG9BdKBUOG0Kk16uE/YQjKxUyU6KG5bTYEAxlGQUio26SgQgeVEgh2Uszuy3iNqAZUvvarWMR15lFWLlmsLrlzrP+YsoG5Pq9Kb12D5CYBcoc3tkCmbQwghj/HEMpx1o6x0kIRkKmBnRPRC66eH7ksqx1k3b7XqaCnrbYAR2xEtBgNcFM71qFF6ReaOeRhOz9Gv+Q1EzCejfVxhZgZ+EJZ5isJwEwxSG2+YBzbUg8qX/lkF3v9HAtQ==
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
