apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    password: AgCBRfFHe5cIvmI70pNUWVTXWUmcmdOOH0JwYcEICMWUxAHXwt5x+HzdinqhGbUfWtGqJb9TaOdyULMAbDFWD6m4aWZLBYzolZXFURwWkzac3WWwgWjPe1H7XlQfxiBVzKP3B4Rke/xnREqe3NVzVBasN5r/pvDNAtFjuh2G4t/VTppMsaxofwDT4C1sg/Qb5MK5FtJqsB2O0psMvOfjMJYdP09fYKN3g+ZVlZazc2/DBCPHsqlQWoQdi4cP2FlAbe3G3uoJCnxsFq5VdpIzR1shBCBxOjfey8wE9nMAb8M+z5+pKauKIEzY+Bpl+XR09LT7MK1qdQ+pScGRLhVSLQdn7qlnG6FnE7ZBrKmPynIcu0dnG/lAW4dBPh2Qq/9lEZaN0VLRFoCkTSn6hwArMzu162jY8SBQlf6eEKykmkcs3tg6n1ofJ+HIupSsmzU6iii7JWgcpm0B3S2houOdapCo1LiNxRp7WqvsliBARVZU1NozsPLugUTD2gVnkir3M0S+MxbxkIzYj+Xqc5kA67bzxjiDpiMfL/lNcTPVvQZaQebnTGcNx0KY9Pj/6nP9UKgw2KkcOv7ZbXjFV/tuUZq+Ihibop9c4jXSb/fd8pUa1uXZTWig5w38qPi5tdm7g8r9aLcealGaqx9NKea5flpXWZcQHWYl4U7SRdjG2QeV5QCMAKlSX4D3RtSyOaVSObpyyEg0jllw9LTJMPDhWRGqDWzLmUREYz7buttffm1sxg==
  template:
    metadata:
      name: pihole
      namespace: pihole
