apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: democratic-csi-test
  namespace: democratic-csi
spec:
  accessModes: [ReadWriteMany]
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi
