apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freenas-api-nfs-secret
  namespace: democratic-csi
spec:
  encryptedData:
    httpConnection.apiKey: AgCkHmkRTiObVRIMj7QyLTgAsQ7glmMQRScaiCDCMn2Wz0PCGfmqTouOiYKCI39GUf5oOGvqe7rcojnBuWXgi/kli65lI3Y2cinWTJQUcdUSjsVMF5i6CXZ08Vqihgdd0Hf7BJrAHOTHnwNURU6XofK7ONeUNC3UhsINbRelq1VHYnPHiDR0yRmJ0y+5nd/QUWawqG4UHdnzCOecGl3AckLJNPIxtg137X/3o1EJWSLKcJ+mIoiLTdVCdWTxRbN+rJHOl2Ifx5B+vgc8nwZFnif2mOP22mbrnT9RFXNSi8LV8zBIkTJuLcBT9d/ikwt9+dBbNiPTftVSkMywTWVwWtmPamFnbGKvo9Q4CZ+9lTKRoxfc+JHC1xzl1eWGVG6dRrFWaI5GA89wzEEjmY7U33bF5wvg+wicpE+T8EAihUhjlG7+XVrKkWAqG3UoaqeUzHL9ns3lt1Jv9fvHxjMFrRxkT39/qzlqDdLdj1MrcRyYmBIZxqXS8/1XFBYvVlUS4dvlx//FHbQjOTTv23PEEAboh2UInEYIxOzT9eXdTBLzerfDoeN1a6fxHIwyL/Vnn2MpwKYh6lC3nHRTM125cwoxD/yjbkOSbMoepz6MfbJATkpUL3+EaO9Tl0+8NCRZnGn2/PTk9Jph54cRomCBdPJPsePf7LrS64YLQJMxJGfjzT5areetROuMbaLNgF1uIUmakLkdbwAyFRsUEkDDneIgEnRMtk+iQVh0vpz/X/PuD/t5lNfh3StsQDpGB3p+d9GGaSwhYOPxaOmzZHphTesx8LQ=
  template:
    metadata:
      name: freenas-api-nfs-secret
      namespace: democratic-csi
