apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bakseter-no
  namespace: argocd
spec:
  description: bakseter.no application
  destinations:
    - namespace: bakseter-no
      name: admin@homelab
  sourceRepos:
    - https://github.com/bakseter/bakseter.no.git
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment

    - group: 'apps'
      kind: ReplicaSet

    - group: ''
      kind: Pod

    - group: ''
      kind: Service

    - group: 'cilium.io'
      kind: CiliumNetworkPolicy

    - group: 'gateway.networking.k8s.io'
      kind: HTTPRoute
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bakseter-no
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bakseter-no
    name: admin@homelab
  project: bakseter-no
  source:
    path: manifests
    repoURL: https://github.com/bakseter/bakseter.no.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
