apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spenn
  namespace: argocd
spec:
  description: Spenn application
  destinations:
    - namespace: spenn
      name: admin@homelab
  sourceRepos:
    - https://github.com/bakseter/spenn.git
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment

    - group: 'apps'
      kind: ReplicaSet

    - group: ''
      kind: Pod

    - group: ''
      kind: Service

    - group: ''
      kind: ConfigMap

    - group: ''
      kind: Secret

    - group: ''
      kind: ServiceAccount

    - group: ''
      kind: PersistentVolumeClaim

    - group: 'policy'
      kind: PodDisruptionBudget

    - group: 'rbac.authorization.k8s.io'
      kind: Role

    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding

    - group: 'cilium.io'
      kind: CiliumNetworkPolicy

    - group: 'networking.k8s.io'
      kind: Ingress

    - group: 'postgresql.cnpg.io'
      kind: Cluster

    - group: 'postgresql.cnpg.io'
      kind: Database

    - group: 'monitoring.coreos.com'
      kind: ServiceMonitor
