apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-copier
  namespace: forgejo
  labels:
    app.kubernetes.io/name: homelab-copier
spec:
  schedule: 0 3 * * *
  timeZone: Europe/Oslo
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: homelab-copier
        spec:
          restartPolicy: OnFailure
          containers:
            - image: alpine/git:2.45.0@sha256:832b1cd1a271509f3d5272a1a62d4cb2ab1a53426ebde1f6c2cb7349f907dc6f
              name: homelab-copier
              command:
                - /bin/sh
                - -c
              args:
                - |
                  set -e
                  git config core.sshCommand 'ssh -i /var/run/secrets/homelab-copier/ssh-key'
                  git clone https://github.org/bakseter/homelab /tmp/homelab
                  cd /tmp/homelab
                  git remote add origin forgejo git@forgejo-ssh.forgejo.svc.cluster.local
                  git push forgejo master
              resources:
                limits:
                  memory: 128Mi
                requests:
                  memory: 16Mi
                  cpu: 50m
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: ssh-key
                  mountPath: /var/run/secrets/homelab-copier
                  readOnly: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: tmp
              emptyDir: {}
            - name: ssh-key
              secret:
                secretName: forgejo-homelab-copier-ssh-key
                items:
                  - key: homelab-copier
                    path: ssh-key
                    mode: 0644
