apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-diff-preview/render: 'never' # TODO: rendering fail because of Kustomize + Helm, fix this
spec:
  destination:
    namespace: media
    name: admin@homelab
  project: default
  source:
    path: manifests/cluster-addons/media/jellyfin
    repoURL: https://github.com/bakseter/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
