resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml

patches:
  - path: namespace-label-patch.yaml
    target:
      kind: Namespace
      name: local-path-storage
