apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-media
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: sabnzbd-media
