apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/falcosecurity/falco-operator/releases/download/v0.2.1/install.yaml

patches:
  - target:
      kind: Namespace
      name: falco-operator
    patch: |-
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: 'restricted'
