apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml

patches:
  - target:
      kind: Deployment
      name: kubelet-serving-cert-approver
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/alex1989hu/kubelet-serving-cert-approver:0.10.3@sha256:4cdc92140c48341433513dce3201806309d5256cfbac6f830feae1e7e9fb0d7d

      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 60

      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 60
