apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/f72897c68e38185aeca848952d10a094054642ba/deploy/standalone-install.yaml # 0.12.1
  - ciliumnetworkpolicy.yaml

patches:
  - target:
      kind: Deployment
      name: kubelet-serving-cert-approver
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/alex1989hu/kubelet-serving-cert-approver:0.12.1@sha256:445a8e5584f659701092d2ec8b625da8929dc75fe4d45274333bd9fe6db8fb75

#     - op: replace
#       path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
#       value: 120

#     - op: replace
#       path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
#       value: 120
