apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Falco
metadata:
  name: falco
  namespace: falco
spec: {}
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: enable-debug
  namespace: falco
spec:
  config:
    libs_logger:
      enabled: true
      severity: debug
  priority: 50
