apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: falcosidekick
  namespace: falco
spec:
  component:
    type: falcosidekick
    version: '2.33.0'
  replicas: 1
# podTemplateSpec:
#   spec:
#     containers:
#       - name: falcosidekick
#         env:
#           - name: REDIS_ADDRESS
#             value: ''
#           - name: WEBUI_URL
#             value: 'http://falcosidekick-ui:2802'
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: falcosidekick-output
  namespace: falco
spec:
  config:
    json_output: true
    http_output:
      enabled: true
      url: 'http://falcosidekick:2801'
    webui:
      url: 'http://falcosidekick-ui:2802'
    prometheus: {}
  priority: 60
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: falcosidekick
  namespace: falco
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falcosidekick
  podMetricsEndpoints:
    - port: http
