apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: falcosidekick
  namespace: falco
spec:
  component:
    type: falcosidekick
    version: '2.33.0'
  replicas: 1
  podTemplateSpec:
    spec:
      containers:
        - name: falcosidekick
          env:
            - name: REDIS_ADDRESS
              value: 'falcosidekick-ui-redis:6379'
            - name: REDIS_STORAGETYPE
              value: 'hashmap'
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: falcosidekick-output
  namespace: falco
spec:
  config:
    json_output: true
    http_output:
      enabled: true
      url: 'http://falcosidekick:2801'
  priority: 60
