apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Plugin
metadata:
  name: container
  namespace: falco
spec:
  ociArtifact:
    image:
      repository: falcosecurity/plugins/plugin/container
      tag: 0.7.0@sha256:4df154dedb0042671d9e4268bc439343a9e189d440ef4c6d01aea8176a552274
    registry:
      name: ghcr.io
