apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: falco-rules
  namespace: falco
spec:
  ociArtifact:
    image:
      repository: falcosecurity/rules/falco-rules
      tag: latest
    registry:
      name: ghcr.io
  priority: 50
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: RulesFile
metadata:
  name: cilium-exceptions
  namespace: falco
spec:
  content: |
    - rule: Drop and execute new binary in container
      exceptions:
        - name: known_cni_binaries
          fields: [proc.name, proc.exepath]
          values:
            - [cilium-cni, /opt/cni/bin/cilium-cni]
  priority: 70
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: RulesFile
metadata:
  name: tailscale-exceptions
  namespace: falco
spec:
  content: |
    - rule: Contact K8S API Server From Container
      exceptions:
        - name: known_k8s_clients
          fields: [container.image.repository]
          values:
            - [docker.io/tailscale/k8s-proxy]
  priority: 70
