tempo:
  tempo:
    registry: docker.io
    repository: grafana/tempo
    # tag: ""

    reportingEnabled: false

    storage:
      trace:
        backend: s3

        s3:
          bucket: tempo
          endpoint: rustfs-svc.rustfs.svc.cluster.local:9000
          access_key: rustfs
          secret_key: rustfs
          insecure: true
