tempo:
  tempo:
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: http://rustfs-svc.rustfs.svc.cluster.local:9000
          access_key: rustfs
          secret_key: rustfs
          insecure: true

  tempoQuery:
    enabled: true
