apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCgMOoV4fnqckhnz3Fo3yEgJYMDmbGKUKOKycUcfOq6Htrlq448+04WviGWvCXKlF9PJIDvcI/BhhjCnswk7U7/ulo/hK5CZSxevmUVeY2y98fajShIqo7ROun9lcIQb7LErv+GpKINX24w9pPewSF8+ur7ngNR0n0Vj6Lfy2YUCpPSh0L/LQFlX+Bb+2UcxVHzD8k1UxUFJJrtDe35rjrHJDJKJlzYqHCHoaTdFVqwCHarAcHtykyIEw68m3J+Th/XRtGOW3l5TVOiOj3sdTt+6DRpn4e5fsZmM1nYlQ/87TiEiC/n2fFCA8DVY25avCA2pjazxVOvcqlXt2mxqFwaXWVsQzc/f348CzRX6DR9CoZIwaewvEEjaYImrg5thcjUdpzaKDXHuDdDMn1lvY+VHSo7HRWRVfDb8rJtoUg3jL+erhqF1mtwjw6hJShAq2hqdBoXpiMDB1o3hqD9yVwKI9sSCKBLhKyeSnmwny9qRnFkkO6/14n8u0/3cpW056wFyszOQzrmSBEUWWKHMBF0GL/uuCctCHm28ieZPz67kO/gYVKVMonjlTJN5iojnb7QbFXU8dUx0qcotywBPMjBtuw6U7zunCeNScBy9QsunAZ4E2WwNULjOyy7pwMeI65/MDdnFiajH9/lWgvwa9+/ObEzaFdE36pHGFPeP9zKAk7YVEfecgxIDmdUg+Kzjk8L1j6WDCUrDqLe+8Bt2dMsNcYPD19+LletEbWMMu8NDCwIQxRSpx9Ru8hKGMOLPY5UJSdbshjtwSJ0tE614P+Ppog6ZNWYaAXed1ZwzeF/GPm2OEDD6cwDC0NSWa10zFX28c0ESbrx7+1S5gbEwU1sFfGLZUQFJ7SmqFptXFa/bK+aaxClDBOA0+2hrMad+Xo66t7PdlVJIm/MRahanuUtVmvGWfv/aKPqYMJv0EcyQG64Y4vQf/y2
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
