apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBDPzCoz+J8B9sSSm0O3kwmd/Gu0/tLYGyVT5N3Wp8ybGsqVkts4NaoZWRYqKeLk6DTioXk9TUksdF1kA70p+I33MimK2N+yu47mxuWlDSEUO8UcX6K+y2H5CdepyosMbhny/j9bFyJM/117hZrQAbdaUYpRhA4Nyb7BJEgYiIOP6tGp81S66pOcYhW38UWfBOCRnyyg2M3B37t+TtlMiXdu90g7qnSBjO8/8Yvztszlh8iPrDJrE+xGxv3DDYO65PTk8LonZrfjRODnIKXoDGeuv/vZ5XyNUmQk5VLGssNivX39heUE49oZEQnb9Xo3MVopCNR+gkQQa4sAmpVvR0K/uI4yxQif5oxDIyJYVnpQxaWvMfoNpMWJgO42BCDJYBvnuVRZKmmb3Yrixu7EMpQlxdmuXEusu6YQAttuaeKHYoWHjusP+pyauA02qlks/sq1g1dSyYC9ngJ21Zh5fC7OduDPdbVIajlIJjRFMxWNUouHP0h2xkBBw4xz7Ih11Npd6tGLdxlTRc9ZhL2lliXdAZoDxrQXslvdcYKWi2MkG+a/soNNpe4lwQHjlsvJXXKOaNvterqkD3CaXnq4SI45RGeqTriCelTfwQV7WAaaeuCR2qS7R2TI8pMwrHLOMA5bhDx7kgc9Tsm/YXoSr8wgq0hbgSpc8H8fITLhii5/UMums8ixNqKYA8DYU998zm9aVxpZMNY6rD3XDD0PjwSCuIycoi0ZsSJIiiCbJeAweSQ36S++4Lf6YvxNEuWUSyJXVb9FaeQ4S59iIiOCmdbXxFsnyfKrfuwLp4j2mmvyzWo8DcNRyYG8ZcmjJC4rfHzyVLycCOHi0vf4ZFmmWVnPVs+g5N4MIkOhR3wqSVQEGdVLzww4ZgwdgPXUA675ZbO1EUzmLimLMdalDftxElYMxLbSRN1JgOOzx+J+O6YWBykZP273kNk
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
