argocd-image-updater:
  image:
    repository: quay.io/argoprojlabs/argocd-image-updater
    tag: v1.3.0@sha256:cb009167015c6212ea21de55dd5734cf123d8b8e95f40ac09b1f1aa1839fad5b

  config:
    registries:
      - name: internal
        api_url: http://registry.registry.svc.cluster.local:5000
        prefix: registry.registry.svc.cluster.local:5000
        insecure: yes
        default: false
