argocd-image-updater:
  image:
    repository: quay.io/argoprojlabs/argocd-image-updater
    tag: v1.3.1@sha256:a578e328e8cbc51badecddea26594247e6d808908d7da8ba127eeb5ac3725f7e

  config:
    registries:
      - name: internal
        api_url: http://registry.registry.svc.cluster.local:5000
        prefix: registry.registry.svc.cluster.local:5000
        insecure: yes
        default: false
