argo-cd:
  global:
    revisionHistoryLimit: 5
    networkPolicy:
      create: false

    image:
      repository: quay.io/argoproj/argocd
      tag: v3.5.1@sha256:0deb1a1c917629b960ead995ae3b6069450a866992676599658687ef9a641ee8

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/homelab.git

    params:
      server.insecure: true
      controller.diff.server.side: 'true'

    cm:
      url: https://argocd.sre.bakseter.net

      admin.enabled: false
      oidc.config: |
        name: Authentik
        issuer: https://authentik.bakseter.no/application/o/argocd/
        clientID: argocd
        clientSecret: $argocd-authentik:clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]

      kustomize.buildOptions: --enable-helm

    rbac:
      scopes: '[groups, email]'
      policy.default: ''
      policy.csv: |
        p, role:org-admin, *, get, *, allow
        p, role:org-admin, applications, sync, *, allow
        p, role:org-admin, applicationsets, sync, *, allow
        g, argocd-admins, role:org-admin

  dex:
    enabled: false
  notifications:
    enabled: false
  redis-ha:
    enabled: false

  redis:
    image:
      repository: ecr-public.aws.com/docker/library/redis
      tag: 8.10.1-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576

  controller:
    replicas: 1

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  server:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

    httproute:
      enabled: true

      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: tailscale-sre
          namespace: tailscale

      hostnames:
        - argocd.sre.bakseter.net

      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /

  repoServer:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  applicationSet:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
