argo-cd:
  global:
    revisionHistoryLimit: 5
    networkPolicy:
      create: true

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/homelab.git

    params:
      server.insecure: true
      controller.diff.server.side: 'true'

    cm:
      url: https://argocd.sre.bakseter.net

      admin.enabled: false
      dex.config: |
        connectors:
        - type: oidc
          id: authentik
          name: Authentik
          config:
            issuer: https://authentik.bakseter.net/application/o/argocd/
            clientID: argocd
            clientSecret: $argocd-authentik:clientSecret
            insecureEnableGroups: true
            getUserInfo: true
            userNameKey: preferred_username
            scopes:
              - openid
              - profile
              - email

      kustomize.buildOptions: --enable-helm

    rbac:
      scopes: '[groups, email]'
      policy.default: ''
      policy.csv: |
        p, role:org-admin, *, get, *, allow
        p, role:org-admin, applications, sync, *, allow
        p, role:org-admin, applicationsets, sync, *, allow
        g, argocd-admins, role:org-admin

    dex:
      enabled: true

  notifications:
    enabled: false

  redis-ha:
    enabled: true

  controller:
    replicas: 1
    resouces:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi

  server:
    replicas: 2
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 320Mi

    httproute:
      enabled: true

      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: bakseter-net-gateway-sre
          namespace: tailscale

      hostnames:
        - argocd.sre.bakseter.net

      rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

        filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: Tailscale-User-Login
                value: "%REQ(Tailscale-User-Login)%"

  repoServer:
    replicas: 2
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  applicationSet:
    replicas: 2
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi

  dex:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 512Mi
