argo-cd:
  global:
    revisionHistoryLimit: 5
    networkPolicy:
      create: false

    image:
      repository: quay.io/argoproj/argocd
      tag: v3.5.3@sha256:dd3f47d5a5e4da563a7a398506e892481b358a7cec50abdf320c71aa55904bfa

  configs:
    repositories:
      argocd:
        url: https://github.com/bakseter/homelab.git

    params:
      server.insecure: true
      controller.diff.server.side: 'true'

    cm:
      url: https://argocd.sre.bakseter.net

      admin.enabled: false
      oidc.config: |
        name: Authentik
        issuer: https://authentik.bakseter.no/application/o/argocd/
        clientID: argocd
        clientSecret: $argocd-authentik:clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]

      kustomize.buildOptions: --enable-helm

    rbac:
      scopes: '[groups, email]'
      policy.default: ''
      policy.csv: |
        p, role:org-admin, *, get, *, allow
        p, role:org-admin, applications, sync, *, allow
        p, role:org-admin, applicationsets, sync, *, allow
        g, argocd-admins, role:org-admin

  dex:
    enabled: false
  notifications:
    enabled: false
  redis-ha:
    enabled: false

  redis:
    image:
      repository: ecr-public.aws.com/docker/library/redis
      tag: 8.10.2-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0

  controller:
    replicas: 1

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  server:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

    httproute:
      enabled: true

      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: tailscale-sre
          namespace: tailscale

      hostnames:
        - argocd.sre.bakseter.net

      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /

  repoServer:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  applicationSet:
    replicas: 1

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
