apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-kube-etcd
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-etcd
    release: kube-prometheus-stack
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2381
      protocol: TCP
      targetPort: 2381
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-prometheus-stack-kube-etcd
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-etcd
    release: kube-prometheus-stack
    kubernetes.io/service-name: kube-prometheus-stack-kube-etcd  # links to the Service
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.30.100
  - addresses:
      - 192.168.30.110
  - addresses:
      - 192.168.30.120
ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
