- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reload and enable offloading service
  systemd:
    name: disable-offloading.service
    enabled: yes
    daemon_reload: yes
    state: started

- name: restart prometheus-node-exporter
  systemd:
    name: prometheus-node-exporter
    state: restarted
