image:
  repository: docker.io/jellyfin/jellyfin
  tag: 10.11.10@sha256:f66273e014b307e4ac46778845ebc1e9ee24b2e57c1fc17d5ec5ac3015649bfa

resources:
  limits:
    gpu.intel.com/i915: '1'

persistence:
  media:
    enabled: true
    existingClaim: shared-media

deploymentStrategy:
  type: Recreate

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
  supplementalGroups:
    - 65534

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - name: tmp
    mountPath: /tmp
    readOnly: false
