image:
  repository: docker.io/jellyfin/jellyfin
  tag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db

resources:
  limits:
    gpu.intel.com/i915: '1'

persistence:
  media:
    enabled: true
    existingClaim: shared-media

deploymentStrategy:
  type: Recreate

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
  supplementalGroups:
    - 65534

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - name: tmp
    mountPath: /tmp
    readOnly: false
