apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-state
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
