---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: runner-token
  namespace: forgejo-runner
spec:
  encryptedData:
    token: AgCUYltVDct9HfDoFlmPnqA0Wa8wCoLJAR7mmkgCXA7nn5eWIjvb9+LSy83bDGYf+wiz6xFUJ5xCq5wc6sUbyTK4O1k+isyaGHfUxI+9COp9WG7n3klNyqxQh1FI8MldEjiYkjGbaNy4iPOVEER5ocCHqF9sDQoWkE71JCdNbidxbHDmHQbGA4ZN6v4HdY4UP4OCnM1mjwbRNeFe3YTBdJEjlfcMDpqGeJZ8rv/UTwBsyTpSRrBNbsRPmMiQ5HOHB2/u7pnqwPfZsQVRdzmn5ng4Rxg7J1IO3w4+oTF8gfvaJ4QhOrPPxIhL8i3WkYzEGiwnMZamGiR/MLVk2MCBCjB4GQuua5oeQA0iVUS5QGviONOF9j3YBpZfCoeWn+btzdF1pHZtAJ63jzUemuyOm6zDTYjZrsz1kMEYx54AD+d0YF+MVbUH1XJp+dfqSEDNCpxPIrMus32nC3KvhxVnRfIQCI+5ybYloyNiCJ11h+agBrrLH5MAd2kp7AKhQDgVUankflai4AxWLWo6WFt+iVndxQbark8ObyHLDWOzcHYh17q2rcUxR4HjFHiE9YWpF7woB9nBX4qkL/zDkrwKKfJkQJF2cWtrQxRDA84RZ66WFVH+Eiin48R3t9dAPJHxtRO/q4qtO89q2xQDdgAGb0qtAIhdZaL8R55oD5aZEVChkRsJQohQZi2l0JLUSOtH9eWKuhjLXHhi7bv3whqDMx0kBc6YMO3rHUF3CcumrxmJ6s1JVW143RkcT/kN
  template:
    metadata:
      name: runner-token
      namespace: forgejo-runner
