fullnameOverride: cloudnative-pg

replicaCount: 3

image:
  repository: ghcr.io/cloudnative-pg/cloudnative-pg
  tag: 1.30.0@sha256:a2701eb97cdd2a34b1fdb2cb51987f544b706e40bec72ae7146cd8580efefebb

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: cloudnative-pg
        topologyKey: bakseter.net/physical-node

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    memory: 512Mi

monitoring:
  podMonitorEnabled: true
  podMonitorAdditionalLabels:
    release: kube-prometheus-stack

  grafanaDashboard:
    create: true
