cloudnative-pg:
  fullnameOverride: cloudnative-pg

  replicaCount: 3

  image:
    repository: ghcr.io/cloudnative-pg/cloudnative-pg
    tag: 1.30.0@sha256:a2701eb97cdd2a34b1fdb2cb51987f544b706e40bec72ae7146cd8580efefebb

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
          topologyKey: bakseter.net/physical-node

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 512Mi

barman-cloud:
  fullnameOverride: barman-cloud

  image:
    registry: ghcr.io
    repository: cloudnative-pg/plugin-barman-cloud
    tag: v0.15.0@sha256:563c680fe7fda3466ca2b1f55a1397ed2ddc9e760360107dd7724f1959c1a536

  sidecarImage:
    registry: ghcr.io
    repository: cloudnative-pg/plugin-barman-cloud-sidecar
    tag: v0.14.0@sha256:9880817c285c7afa4d195da2145064d21907405489ed6ec39abe59b1feb558a4
