cloudnative-pg:
  fullnameOverride: cloudnative-pg

  replicaCount: 3

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
          topologyKey: bakseter.net/physical-node

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi

barman-cloud:
  fullnameOverride: barman-cloud
