apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: nightly
  namespace: velero
spec:
  schedule: '48 */1 * * *' # TODO: change
  template:
    ttl: 168h
    storageLocation: hetzner-s3
    snapshotMoveData: true
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
      - sealedsecrets
    labelSelector:
      matchLabels:
        bakseter.net/backup: 'true'
