---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBLSCV4mBtw2i3ibN3oVs+fX92XGWxmHly+J8wSqC2PnxXhE9/yRiqteI37FKDlCzb/cxBci7bDAi+gxw94916fZmbkSVfHcE4dTHiDprl2Lph5vceaJRnBUy6+Euup+OpYygtEYTD34/xZOIxttHwenw4yOXJ1oZXrZ4f+nHrqYUWJ8I+YBlAqzpH1Z7hTy9Ejm/VOFr3rM1imck9EAdPienvjetTRtt7bXAHrEOwaT+wSDdaPmaXM3MS+HZQ8kO0uN5W2P+TTxd/WDJx9uy3JbnAhXgD4VXTTyuqEYAwgf1KN9ciEeETidUDJ0PPjDNDN2lJEnmC7RjKt1fHbIg04ZjzVGayj7VN1z/lhrUKd69Eml2m9CXCjZDCsxXn2Ex1QcKjelGZ/FfAYzhJfj+nGyJJzxJwCuSkcubQlqH//BZiNCdyS/tJ9eVU00vPTk5LLeERauB/fM+zmCOLTTn+S0R65PBLcoCxXDiMyW8aoTY7pdCXQBjC5x6QzVCptuc9y+anUMDEJj/IU/68LWnz45VtNJ38MRtAS7jmZWqq+gAPwl3ZiNm4Tm22y8tu9LNkcR29jcBRqeOjfFup2AiXBhmSWIsTqNIDR2z2j3G5QgCXD0YK577ExKIIcmxPd2NWdd0Zqgejqcc3hRXzyPMf4DiTiOyIvuMxV3S3q0tZ56RVJgWHvsfZi/EjoJHPpChWwPNDnzqNaAsvTpbM2VmOJXej/N9Nf5x7uwU/52cz+1i3MWh259J/tzAtvHZZz6LEVfnfQEh+xmIWngjPfLTZp/Uj3sc1RsOlYb6xQW06WzjKpfuKtF0N6zUQelZQDL5pE1W6aGn2/52oXuA75Z6c=
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
