seerr:
  ingress:
    enabled: true
    ingressClassName: tailscale
    hosts:
      - host: seerr
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - seerr
