apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnpg-primary-pvc-labeler
  namespace: cnpg-primary-pvc-labeler
spec:
  endpointSelector:
    matchLabels: {}

  ingress: []

  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: '6443'
              protocol: TCP
