---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kagent-mistral
  namespace: kagent
spec:
  encryptedData:
    MISTRAL_API_KEY: AgCCdF1IzowMH1su7r/4ulxA+KlK060otYupfdIWdrJlPYA6GaNFKDRpNNKncCvrquPOGdUErrBekYqE6BYm739qH93+YeaEVgFLxKcTZPOGkcpeZaQYr7bGwbJRrVc6Ugi2N/9hJdCJ3rHEAq7MRoWE9LATCdVpm3C6Bm7W2gAMtoAxJ18EDuOqEyFgI6J8kKSbSO3U4JGXn0O4EefeH3zIODcup/x8prnD/wZ8uAt6B97CxAB1bYroEw8kHDVpYisps5U2pYYXg3VUiAV0pSMZyHjIXNZNPKmuQjf64SVUTqrUzH9LF7HsdBgVkQ6Omhpm3zFJAXVYzZmeuGJPyBCZyUSQ3JTxhuxxwZt4/eHcm+EA7aYmQpVZXa+dyBvhSBDifcwQ4N8hh99toUt31+FXyGUSz2yxXMpllF3jZGapcqAqXBL5Xfw0NhaM4ZlgZguTmLWhQ5BkXKVJYtg8zG7LgBlR+zQ2CX5m8JkK1yzNrVNmKFSIOekP7f+uXw+z5PsoQNC+kYxRm3C0+J57wapiwzyQGtLgJYlKiNkSECsxe2SvV4AEoxzGsdOCAt+rnhRssSt2/FGPRRVF1SZKT2Nr92gz3K8h0Ai3Wje3OcziuqlqfQdp5qTLqyOTGJcUHTT0x5Bde+vzDcPU+5GxeiSUveA6d6S0E/uJA81MUHgZ1AHVUZwpCLuBQa6WHUtK9CK9hUxj+J8jbDqzL+7MsuJW+xRoJw9t1QjotaY3vaqXEQ==
  template:
    metadata:
      name: kagent-mistral
      namespace: kagent
