apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kagent-mistral
  namespace: kagent
spec:
  encryptedData:
    MISTRAL_API_KEY: AgCCdF1IzowMH1su7r/4ulxA+KlK060otYupfdIWdrJlPYA6GaNFKDRpNNKncCvrquPOGdUErrBekYqE6BYm739qH93+YeaEVgFLxKcTZPOGkcpeZaQYr7bGwbJRrVc6Ugi2N/9hJdCJ3rHEAq7MRoWE9LATCdVpm3C6Bm7W2gAMtoAxJ18EDuOqEyFgI6J8kKSbSO3U4JGXn0O4EefeH3zIODcup/x8prnD/wZ8uAt6B97CxAB1bYroEw8kHDVpYisps5U2pYYXg3VUiAV0pSMZyHjIXNZNPKmuQjf64SVUTqrUzH9LF7HsdBgVkQ6Omhpm3zFJAXVYzZmeuGJPyBCZyUSQ3JTxhuxxwZt4/eHcm+EA7aYmQpVZXa+dyBvhSBDifcwQ4N8hh99toUt31+FXyGUSz2yxXMpllF3jZGapcqAqXBL5Xfw0NhaM4ZlgZguTmLWhQ5BkXKVJYtg8zG7LgBlR+zQ2CX5m8JkK1yzNrVNmKFSIOekP7f+uXw+z5PsoQNC+kYxRm3C0+J57wapiwzyQGtLgJYlKiNkSECsxe2SvV4AEoxzGsdOCAt+rnhRssSt2/FGPRRVF1SZKT2Nr92gz3K8h0Ai3Wje3OcziuqlqfQdp5qTLqyOTGJcUHTT0x5Bde+vzDcPU+5GxeiSUveA6d6S0E/uJA81MUHgZ1AHVUZwpCLuBQa6WHUtK9CK9hUxj+J8jbDqzL+7MsuJW+xRoJw9t1QjotaY3vaqXEQ==
  template:
    metadata:
      name: kagent-mistral
      namespace: kagent
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-creds
  namespace: kagent
spec:
  encryptedData:
    credentials: AgAkP+kzefAuTy5gZy0RoppyGUMcYk1dRpo5Z2QEAF29OeYwhLRnemOe1DzGj9c1yBLqd7fzZAUSwkCUCcKBQjJPSk6sfkbe4JDEL2Ha8VmQezPviUdzEg/ajolfOsUSxuMfwFSepod2SrJjCjtm/SwXezfabpXwJcxbM2GufNvcmnw/XSN0T7Ymwo0znZ048dtwdQOZoYusFd2HCHccvF+JDoDRId8PvTkvgs2QDIRZ/mWWpvJLq9/WPpwA4PumI7I8mf+OW3BAjGDlixGUQ9RHlPFfd14Xbj18UCd3lsZgpU5HSQTILAjBtugD/7Teu537U0JjMNUP7yiMihxcIUKznYKETaGr58EA/VNZ6u18dT1SjV8aFf4H2kCRztAWlhfldMNWJjLAUoDPRY5sw3Ho/SyVKdAt1Ew2MbySCtyccHtmtdJDPLj7ZGux6xBhrIuQUNZLFeV2rS5Kcxi1oE44A7sFgk1bOLOiwR6BhCIju19zuLaCqv+bBadU9/y3bQt8wwL4GF2EDVrLVhsc0C4llHry3L8xnVTCkqXS6p/o3QFUEsbbdToqd6FLNAFg0Jq+lhhufHhsAsGpBMQxGVudV4ir5cs4bI3dAuqlT4/av+PrEfJHCZkpMxUEYFPLllx94WXk9hnQP9mWAWSLBmtbrJi4LBs3ltZKJCk8YgvCiE9s6vDyFLj5a625/zYIo5PWZ5jVFcyPxBpD+GJx9uY9LJG9w0OgGMX5+TVyD4mDpZ7X9qxTq+H1ZrIzXGqr4eik2QzUQzkckNvepsiQ+xJSUGEnnaG9XnEy1hWjJAOUJnMHy0qyewcWmn1KLA5cpjf4YY0=
  template:
    metadata:
      name: forgejo-creds
      namespace: kagent
