apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgAqXstG16+DJCVSeoZe5RYqq+02TMAdykF2rNQdh3JVWxylwqf99MAQR5RAQNKmkAnSp7RY6yLn8HJ5yNQiezDfDg55A1QUSZG68/dGMF7SxHOjepcl5vFrLvekhZTLnyFvl3GGdiduDeED40VtsW/TQbxZmEolGlklYe1xbHJfjkVrtLPx54iGIOZVsyYJbTUTG9Ei8gk3+s9rhPVcCja8ljP52ioMfQwHE674TH67u/WP5/VMa0mj3eFvchn2rFhiXV+WWD+a6+L+jkfFudMuSiXM3aOl/+K2VtdcgVZjv2ZMhusc6IhYXb/se43S/qBR0AV5V5gFxL0lRnS1VCCA/qE3DroZgIR9A+wzsSHwOuYZVF+hTU1NGsuC7R0w83fcmhLeAdSqovvPKkS+AMVTIUQWlhJndHsg3Jxnn6kl8IVx9Fe6+eWObi+J1MBke1ErLoS3ij+3Zc40PJPVoaQFPIsrocgAvf7mOr8KVanullxStNXGUMADXbcIsC4ffBKQspK3yfZDSrN3rV5YGs8XUYzu6KvNjGVbBf/1NZmksxqddzFULYlaAjnEU0j0SAOrGX2+T84ACM9W5t9t8RxEPdOPEG17o2KzRQ9Nylt2hoTIUkJANM257gmUajTBbMds2t58Nyza1Q0rchrRYvdQK0PQRgzpqQ4ovhhtBYF+cPAx8VsE4qvSw9I94lLirFtXM+zduOApqeoqvZEq/9WjzYi6Sdnpc5JRm/LAISXy1A==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
