apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgCZUJoHqhqHb0WZ0a7SdZKzrX4rPIPaauOwgyvP1pJ5+DeK3xbDog0a7V1/TmrSfYDxxmwVWfHkERgSrUOy1k6OToBa3RAYDO3R7X9aB2pRH7/a7YoIOdyXUAkrFWpJuPuEIQwUBnEC640Cl2Q0e2rNS5E0QAChZkvTUcKVQF9K/DekhCj1RMUUfiAe8KEl6WZgm6EzzacwiNcVsV//lJo8GSz348hYyArio1cck9X+5JUPw5KcKuH301+EQw7TXIhS8TK0qoIZ1LlNm2poDFPjyWqPJpwcFw51DUHoJKBKEOc8kU1I/oUYcNE/xX3vyqqAnIp2aQ1uivTZ/t9Jo1N0Xr6u2dB0kwvEhyVt9GJHm5ysf3e1EpEa1ednl/2evEJKBNxR7iqoAOdM1etkVxK71xVjI7EvyrRruufvooLhXFMPH/tZwg24znT5ecrvuyTTbiIaOoi6yFyOMtfmy5Wssq2sLekT00uz1ROD9vZYrX7pfA7t9pkhJ0pCYiFG2K/2ZLyUMuKRB6H799Psv4Y09Fn2GHKVrDFtnx+cgyUb/2kxzlXkCYpLEB8ufW39pzEBOtRsGc2d0QLz8mUy9paemUe3xq2msNjowHi1HWsld9cB7+UzAKvpwcufLamdn8fJEuwJ52tPKDfCjL16kuTseRQB3fIZx7Ms6VQdxcanMuG9rBvW2idn9tkSmpijYGfgyIuASZHmUa6dTfHQ1qufbQdiE1ZZhWXNKu4tTyKEsg==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
