apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  namespace: authentik
spec:
  instances: 3
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job-group.longhorn.io/hetzner-backup: enabled
      recurring-job-group.longhorn.io/fstrim: enabled
  affinity:
    nodeSelector:
      node.longhorn.io/create-default-disk: 'true'
    enablePodAntiAffinity: true
    topologyKey: bakseter.net/physical-node
    podAntiAffinityType: required
  storage:
    size: 6Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
