apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-database
  namespace: authentik
  labels:
    bakseter.net/backup-primary: 'true'
spec:
  instances: 3
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job-group.longhorn.io/fstrim: enabled
  affinity:
    nodeSelector:
      node.longhorn.io/create-default-disk: 'true'
    enablePodAntiAffinity: true
    topologyKey: bakseter.net/physical-node
    podAntiAffinityType: required
  storage:
    size: 12Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 2Gi
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: authentik-database-3
          kind: PersistentVolumeClaim
          apiGroup: ''
