apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-server
  namespace: authentik
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cloudflared-gateway
      namespace: cloudflared

  hostnames:
    - authentik.bakseter.no

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - group: ''
          kind: Service
          name: authentik-server
          port: 80
          weight: 1
