apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: authentik-pooler-rw
  namespace: authentik
spec:
  cluster:
    name: authentik-database
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: '100'
      default_pool_size: '20'
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: authentik-pooler-ro
  namespace: authentik
spec:
  cluster:
    name: authentik-database
  instances: 2
  type: ro
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: '100'
      default_pool_size: '20'
