velero:
  snapshotsEnabled: true
  deployNodeAgent: true

  image:
    repository: docker.io/velero/velero
    tag: v1.18.3@sha256:b839e52bc2c69eb3b5a84b010b8b3c7f714f3c5ef50b77ec7770a382a8f2e0ab

  extraVolumes:
    - emptyDir: {}
      name: udmrepo
  extraVolumeMounts:
    - mountPath: /nonexistent
      name: udmrepo

  configuration:
    features: EnableCSI
    uploaderType: kopia

    volumeSnapshotLocation:
      - name: default
        provider: csi

    backupStorageLocation:
      - name: default
        provider: aws
        bucket: bakseter-homelab-velero
        config:
          region: eu-central
          s3ForcePathStyle: true
          s3Url: https://hel1.your-objectstorage.com

  credentials:
    existingSecret: velero-s3-credentials

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.14.3@sha256:74597d39c143d4d7bc66a27f62a627947715c60ce498b9dfbbd6513f2a113030
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
        - mountPath: /target
          name: plugins

  nodeAgent:
    podSecurityContext: {}

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    extraVolumes:
      - emptyDir: {}
        name: udmrepo
    extraVolumeMounts:
      - mountPath: /nonexistent
        name: udmrepo

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    supplementalGroups:
      - 65534
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
