velero:
  snapshotsEnabled: true
  deployNodeAgent: true

  image:
    repository: docker.io/velero/velero
    tag: v1.18.1@sha256:11459094b1b21ec7c817b08f8067d9e89380835547915cac9c4132ff05b55b90

  configuration:
    features: EnableCSI
    uploaderType: kopia

    volumeSnapshotLocation:
      - name: default
        provider: csi

    backupStorageLocation:
      - name: default
        provider: aws
        bucket: bakseter-homelab-velero
        config:
          region: eu-central
          s3ForcePathStyle: true
          s3Url: https://hel1.your-objectstorage.com

  credentials:
    existingSecret: velero-s3-credentials

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.14.1@sha256:1493a0039cd5cb31004cfbb52f8a1990bc0ed81497ce72516bc76fa9e21506c1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
        - mountPath: /target
          name: plugins

  nodeAgent:
    podSecurityContext: {}

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    extraEnvVars:
      - name: HOME
        value: /nonexistent
      - name: KOPIA_CONFIG_PATH
        value: /scratch/kopia/config.json
      - name: KOPIA_CACHE_DIRECTORY
        value: /scratch/kopia/cache
      - name: KOPIA_LOG_DIR
        value: /scratch/kopia/logs
    extraVolumes:
      - name: velero-home
        emptyDir: {}
    extraVolumeMounts:
      - name: velero-home
        mountPath: /nonexistent

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    supplementalGroups:
      - 65534
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
