velero:
  configuration:
    volumeSnapshotLocation:
      - name: default
        provider: csi

    backupStorageLocation:
      - name: hetzner-s3
        provider: aws
        bucket: bakseter-homelab-velero
        config:
          region: eu-central
          s3ForcePathStyle: true
          s3Url: hel1.your-objectstorage.com

    features: EnableCSI

  credentials:
    existingSecret: velero-s3-credentials

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    supplementalGroups:
      - 65534
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
