apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgBD4ZsS3du2CV3XKpT2cC221sln5suKZXJspbTQ83p4AhrRM8KynXs6yfkeASghiS6m8/V06l2Lvhc84pp0j9lUYCGug65ZqoQGDCUz2cvD0OZ20tE0XQEgZw/ddtxE7cy12WkdyXAZVV9f3sdCztD+wrIT/sICYlfu0wtWKUX8ggoeqiUkSbKsOtasmtn4ukpw80cVLtqM9sBlZbcB3mZSAKnQ1zASmYtHVcrFGmkMySxeO117CA/mwVYfeUBt2lwQM2PdcIvJKkg6DiOdsIDFgW/qy9CV4KaNNO1KQFjBg4dhkFyaWr5axKCIw/d3fzqjP6V5X/tcQwhL44uh0oFNTrjpi5j3UNXaKCMJIrB3IPyV8RgV0BNpALxI1K25amyqKoidCIFZ2WwyUosVT1t0oxSYRosdoKB3kMIb6s/Qw5eqOaLQ87Oa2h9B1tWfDaMczj0z1rxkEx9AGtU9AmqvWfg/erPbWBgKicbPLqtkJkTt1h1JvoZJSEE7aAQnl4KbuYKtmU6cNRXZ9laNvH0YNFKzjUamc2TFDqokAgzzd50hApGtLZmODqG560Jxo53xifApuE/T8orSAWzweO4OmtdHXmwXKALi3ZNZk3ZlSjj8qRhBQva+1tYLmIGgk2W8HtSb57mqMce0bkAoOzSvUfWPnUJigOVLDyC5Im7+XWmhzemnqfkLiFbx2aPxw9Su+85Qb2UUgqciy6a7kdnHBTsNimC8C6fobQ3QJK4cuw==
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
    type: Opaque
