seerr:
  image:
    registry: ghcr.io
    repository: seerr-team/seerr
    tag: v3.2.0
    sha: c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad

  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/tags: 'tag:k8s,tag:media'
    hosts:
      - host: seerr
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - seerr
