node-feature-discovery:
  gc:
    securityContext:
      seccompProfile:
        type: RuntimeDefault

  master:
    securityContext:
      seccompProfile:
        type: RuntimeDefault

  worker:
    securityContext:
      seccompProfile:
        type: RuntimeDefault
