apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgA22KoTEYdCTSYD7zcmgPo1rlaC7CBpp5InCGrGBG1DdBCV2YKLrg5zhRj3AzrOcHLA0CGOONzPchE1jj2jUZXvqF+oVDuUFjFUm0dXGe7Tl7aNdopDbv90Ydh7H/C4EA2TNZAIBam/IHrkgOjxzBqPCpmANVsbBEALaTizGaJYdFmw+B0CqzkVkCeAVPmvela+lZPjGXjPQpULV/rwsgFzYs91u8syXNbf4vC4ONoyNcZlD2NIWWmBQ7cDaFH/sHbKuhXu+J9ni3ZGK1OmUulDCjBAjOcbs8G+bN9ZB/nnX5vRxzUYUvHOl44cOU9x4z75qQGiKwp7sg/CzXCQDPWcUxrRj0OTtUjRih4voT6WuFbQF22ECyUH/0NVVYoarXiEWr/6CFMOMtu71iTh1iYL36QA/4JSgfUMDqAZNhmGaef5FyMMeMrjMA9itgJR7FmJJ0W3eMl5ITwj/y8spz1e3HJQ02XWRwgCxFxMM6ufaE25oDbNxtGQiBDvd46MP3ho/O9ZhWjdyCd6rWNaOOXSJ6qgzsF8xGuIzMpMq6HkUErfdCzGNoGVrXvAGXGzHtq1rrvJwSL1dItIOGJGBSuQwOY52iaNVXTFGYPxRFtEq7f26VTTatyU+5HJFlG/8ssrZgGYGbPO+y/B5iV+CuorRI03V649l6FnQhoSbBVAaXhRBoHbnimz6Z54kEnUJxbnx62Ii8+dCRvEjzfiSPAjPHrf7tdkX0jtBZCw0O36Cgiqt54UHnrtmQPAXN3lmovhQjQr/fpvLc0MuTq3C9QiFp0cd+A5CABSGqKPzcWwXSp/cR4YgqKqQVsUlZPIeqfREQpZJzlBS02cAnjn5Rd7b3l7O1DKkFO80SUgTF7UpQ==
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
