apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  httpRoute:
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: bakseter-net-gateway-sre
          namespace: tailscale

      hostnames:
        - grafana.sre.bakseter.net

      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: ''
              kind: Service
              name: grafana-service
              port: 3000
  deployment:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            supplementalGroups:
              - 65534
          containers:
            - name: grafana
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              env:
                - name: GF_INSTALL_PLUGINS
                  value: 'grafana-lokiexplore-app,grafana-metricsdrilldown-app'

                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oauth-secret
                      key: client_secret
  config:
    log:
      mode: 'console'
      level: 'debug'
    server:
      domain: grafana.sre.bakseter.net
      root_url: https://grafana.sre.bakseter.net
    auth:
      signout_redirect_url: 'https://authentik.bakseter.net/application/o/grafana/end-session/'
      oauth_auto_login: 'true'
      disable_login_form: 'true'
    auth.generic_oauth:
      name: authentik
      enabled: 'true'
      client_id: 'grafana'
      scopes: 'openid profile email entitlements'
      auth_url: 'https://authentik.bakseter.net/application/o/authorize/'
      token_url: 'https://authentik.bakseter.net/application/o/token/'
      api_url: 'https://authentik.bakseter.net/application/o/userinfo/'
      auth_style: 'InParams'
      use_pkce: 'true'
      role_attribute_path: >-
        contains(entitlements, 'Grafana Admins') && 'Admin' ||
        contains(entitlements, 'Grafana Editors') && 'Editor' ||
        'Viewer'
    users:
      auto_assign_org: 'true'
      auto_assign_org_id: '1'
