external-dns:
  provider: pihole
  policy: sync

  extraArgs:
    - --pihole-server=http://192.168.60.200:8080
    - --pihole-api-version=6
    - --gateway-label-filter=external-dns==enabled
    - --registry=noop

  sources:
    - gateway-httproute

  domainFilters:
    - bakseter.net

  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-admin
          key: password
