rustfs:
  image:
    rustfs:
      repository: rustfs/rustfs
      tag: 1.0.0-beta.8@sha256:fa19210ac4697c79d7ccca1ec9b0eb91aebacc6691991ffb14014bb3c67e6cc3
    initImage:
      repository: busybox
      tag: stable@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662

  mode:
    standalone:
      enabled: true

    distributed:
      enabled: false

  replicaCount: 2

  config:
    rustfs:
      log_level: warn

  secret:
    rustfs:
      access_key: rustfs
      secret_key: rustfs

  storageclass:
    name: longhorn
    dataStorageSize: 20Gi
    logStorageSize: 2Gi

  ingress:
    enabled: false

  podSecurityContext:
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault
