harbor:
  updateStrategy:
    type: Recreate

  expose:
    type: route
    route:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: tailscale-int
          namespace: tailscale

      hosts:
        - harbor.int.bakseter.net
