apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: tailscale
spec:
  encryptedData:
    password: AgAB9NJtPeAyvVJExFDdjzK3yyQAkeZtqH1coBhZ2O6t2YMi7z5EmIGmDoSoO1R4fTRvrQkjW/rX35sE7JR6jUUt7jvP+dIFx3X9NDUMqQDKnWisOHOpjCaaAhROceajX8F6Qd35sYeRs0kpMjOmGBUzOSUdflHxVrC+2tg/qyS4LAlbNkuBu7FGaL/kPq/BuQyCy+SK9Ddt+83ynQPHWKLCk5CMzXyADOw2ZerdyOlMu8xKXlSwqhtKGTYR0AFdtLr6lhG5Ag5NXtSV0tbPJgTX7/humnoKWmmIaeiuynLc3EYygdhVkJ1wnPzf9V0QLHQa4NmoQspJWwqVcX6o0BlkNas5Xz0kDyg8/msmBisBXl3ocTq9ZTJ7e+WOjHcSwmEUMcV5yHgYoT7Re73ytqpNJzWu+0gFaN0a/xfz8EQStZ/UfgW+jYyETtBw01VM3bFbcHYWl7xmCfTsRX7NOxNFVnxcRheCXeGlG1aifQscem8OyQ3xubDYh13HlmbIGT7fZM6ERjG/ijxTVcV7mNzmER+Fa4vTVL6/fr1w9MAYGf2q3Q11C5c5I9/Pcb/k4IGN9C1OykqmjSb8Y86g3vsc2gki4dpZvtQ8BUo9Sp46q/gCoE/bG6OeHEKfM71jEpBudg7PcziivjEEJ8cP3zJUtj/x1Sb5JgNQNVRl7yOfxjuiiprTz/XkGw34qeRRd+H7LLHjMmb37il638s6uTI/onX0FfgaDAC8J4uajuBAaQ==
  template:
    metadata:
      name: pihole-admin
      namespace: tailscale
