tailscale-operator:
  operatorConfig:
    image:
      repository: docker.io/tailscale/k8s-operator
      tag: v1.96.5
      # takes precedence over tag
      digest: sha256:7ea50edd505a7e5502f9f424e7d1670151ea97cc0e2d2b7c1772c53a158434a3

  apiServerProxyConfig:
    allowImpersonation: true

external-dns:
  provider: pihole

  extraArgs:
    - --pihole-server=http://tailscale-operator-pihole-web.tailscale
    - --pihole-api-version=6
    - --gateway-label-filter=external-dns==enabled

  policy: sync

  sources:
    - gateway-httproute

  domainFilters:
    - bakseter.net

  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-admin
          key: password

pihole:
  replicaCount: 3

  admin:
    existingSecret: pihole-admin
    passwordKey: password
  
  serviceDns:
    mixedService: true
    type: LoadBalancer
    loadBalancerClass: tailscale
    annotations:
      tailscale.com/hostname: pihole-dns
      tailscale.com/tags: 'tag:k8s,tag:dns'

  extraEnvVars:
    FTLCONF_dns_listeningMode: all
