tailscale-operator:
  operatorConfig:
    image:
      repository: docker.io/tailscale/k8s-operator
      digest: sha256:59060effe5baeeac7909f23871549fbbd9da78dd5b03af8c89bccb35ba46e93c # v1.98.4

    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault

  apiServerProxyConfig:
    allowImpersonation: true
