tailscale-operator:
  operatorConfig:
    image:
      repository: docker.io/tailscale/k8s-operator
      digest: sha256:eaef921470ada74a84ca8bbbf4a6a89452ed2581d51a0551758507aca8dc2a01 # v1.102.2

    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault

  apiServerProxyConfig:
    allowImpersonation: true
