semaphore:
  general:
    useRemoteRunner: true

  # runner:
  #   existingSecret:

  database:
    type: postgres

    host: semaphore-database.semaphore.svc.cluster.local
    port: 5432

    usernameFromSecret: true
    passwordKey: password
    existingSecret: semaphore-database-app

  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
