semaphore:
  general:
    useRemoteRunner: true
    #nonAdminCanCreateProject: true
    #passwordLoginDisable: true

  admin:
    create: true

  image:
    repository: semaphoreui/semaphore
    tag: v2.19.14@sha256:98ad9bc7a2a03001a725c90d37c9e500b951da3175d51cd36337e9c1cf7ea9aa

  database:
    type: postgres

    name: app
    host: semaphore-database-rw.semaphore.svc.cluster.local
    port: 5432

    usernameFromSecret: true
    passwordKey: password
    existingSecret: semaphore-database-app

  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  oidc:
    enable: true

    providers:
      authentik:
        display_name: Authentik
        provider_url: https://authentik.bakseter.no/application/o/semaphore/
        client_id: semaphore
        client_secret_file: /var/run/secrets/authentik-oidc-secret
        redirect_url: https://semaphore.int.bakseter.net/api/auth/oidc/authentik/redirect/
        scopes: ['openid', 'profile', 'email']
        username_claim: preferred_username
        name_claim: preferred_username

  extraVolumes:
    - name: authentik-oidc-secret
      secret:
        secretName: authentik-oidc-secret
        items:
          - key: secret
            path: authentik-oidc-secret

  extraVolumeMounts:
    - name: authentik-oidc-secret
      mountPath: /var/run/secrets
      readOnly: true

  extraEnvVariables:
    SEMAPHORE_WEB_ROOT: '/'
