authentik:
  authentik:
    existingSecret:
      secretName: authentik-secret-key

  global:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2026.2.3
      digest: sha256:7806ae1ae3423624fe90331e8b3dcca0afc155fac890c696dd92ddac6dc3a384

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
        - 65534

  server:
    replicas: 1

    #   affinity:
    #     podAntiAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         - labelSelector:
    #             matchLabels:
    #               app.kubernetes.io/instance: authentik
    #               app.kubernetes.io/component: server
    #           topologyKey: bakseter.net/physical-node

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 1536Mi

    env:
      - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
        value: 10.244.0.0/16

      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secret-key
            key: secret-key

      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: host

      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: user

      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: password

      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: dbname

  worker:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi

    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      timeoutSeconds: 10

    env:
      - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
        value: 10.244.0.0/16

      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secret-key
            key: secret-key

      - name: AUTHENTIK_POSTGRESQL__HOST
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: host

      - name: AUTHENTIK_POSTGRESQL__USER
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: user

      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: password

      - name: AUTHENTIK_POSTGRESQL__NAME
        valueFrom:
          secretKeyRef:
            name: authentik-database-app
            key: dbname
