nextcloud:
  httpRoute:
    enabled: true

    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: bakseter-net-gateway-home
        namespace: tailscale

    hostnames:
      - nextcloud.bakseter.net

  nextcloud:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
        - 65534

