apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: fs-mcp
  namespace: kagent
spec:
  transportType: stdio
  deployment:
    replicas: 1
    image: ghcr.io/bakseter/homelab/mcp-tools:1@sha256:c4999e544ae0e9d6bc433ce07ecc3248a9a068231e6108458f1d09858ea710bf
    cmd: mcp-server-filesystem
    args:
      - /workspace
    env:
      HOME: /home/node
    volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: git-mcp-fs-mcp-workspace
      - name: tmp
        emptyDir:
          sizeLimit: 128Mi
      - name: home
        emptyDir:
          sizeLimit: 128Mi
    volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: tmp
        mountPath: /tmp
      - name: home
        mountPath: /home/node
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
#   tolerations:
#     - key: node-role.bakseter.net/agent
#       operator: Equal
#       value: 'true'
#       effect: NoSchedule
#   nodeSelector:
#     node-role.bakseter.net/agent: 'true'
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: fs-mcp
  namespace: kagent
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: fs-mcp

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kagent
            app.kubernetes.io/component: controller
        - matchLabels:
            app.kubernetes.io/managed-by: kagent
            app.kubernetes.io/name: homelab-agent
      toPorts:
        - ports:
            - port: '3000'
              protocol: TCP
