apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: github-mcp
  namespace: kagent
spec:
  description: Read-only access to the homelab git repo.
  protocol: STREAMABLE_HTTP
  url: https://api.githubcopilot.com/mcp/
  timeout: 30s
  terminateOnClose: false
  headersFrom:
    - name: Authorization
      valueFrom:
        type: Secret
        name: github-mcp-pat
        key: token
    - name: X-MCP-Readonly
      value: 'true'
    - name: X-MCP-Toolsets
      value: 'repos'
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-mcp-pat
  namespace: kagent
spec:
  encryptedData:
    token: AgAnb9Tgg04fSLoVYKwobvQUn0l6IMbL2AV1+gDNRro/u4k8ECh75QwN1h6fRhu8ZMUz3vTr7XomXAFbuI0VH8ni+ARXpyO1NQKwXua0yq0CcbywpgaXZ1tkrIAZ18MDnCl2hn7hR2+w2bJH37l6O8m68A6KTYIWVcOoZKP8VnbNY1uw94DTX3ARRYRpNNhSaHH+lMYnHUnPAIEsFRdqznlkqYX/2HSkwuI383LzcSkW0iI/kiFMq/bNrYCZ66woszrtWmve6aoVTCpHzzopdFBmmFH9V/mf6Jfs3DvnlEQ0cpqtZUpkFto21uyJ4K4eFNq77Ig6OJ67L7gA4ZT/2YizP3YoJHrJfkhOOG5fECkwk8rPxEk4t87mRG7Vg8SF97gNNJw+mIAKNvkD8Mq+CAh6Uujtd/pQJcCoKNzshcVAxeJQu0FXO92fmfAABgf+QR20iX54he3dCkQQ75mPYnnaBp8BkMCVLtONFXcsAUs5taXxd0BCzTNaxhKYVMLZfkg9bL5MWVHcCJNfgXdNNCFZ+c+Odufzc0vvK+y86gbi3yM9YpIr6/S33aNZ82+zFaEuS98mrNyIvHKY9bVUg1mkWy0AqDq5b21rmjkXvI065b8ywEy30UMh9HOdcAzmQlkEb1r5dsXK8oXPobzJhM9ryJtFYH+YLSHpNhjECOVDkKQTbsxUAcSoFy2+X1316JXQcAsVhoWD44bdecPF4rrvdf1RpNkTdRPNkyXGUxER2evS/Afh+3wcuv6OfFql/6PDcgCnnzbsv9jirPIi56695xeHo5BCfU7eurGxw/1zi5uALaYqnYOoOfr9py0=
  template:
    metadata:
      name: github-mcp-pat
      namespace: kagent
