apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true

  settings.yaml: |
    title: Homelab
    headerStyle: clean
    statusStyle: dot
    hideVersion: true
    color: slate
    background:
      opacity: 20
    theme: dark
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: homelab
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true

    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23

  docker.yaml: ''
  proxmox.yaml: ''
  custom.css: ''
  custom.js: ''
  bookmarks.yaml: ''
  services.yaml: ''
