apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: 'true'
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 1000
      containers:
        - name: tdarr
          image: ghcr.io/haveagitgat/tdarr:2.74.01@sha256:4dd21e8aa92f10601c35828566ddaadbb6d9d4335d004411ee69f1e02714d1c8
          env:
            - name: TZ
              value: Europe/Oslo
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: serverIP
              value: '0.0.0.0'
            - name: serverPort
              value: '8266'
            - name: webUIPort
              value: '8265'
            - name: internalNode
              value: 'true'
            - name: inContainer
              value: 'true'
            - name: ffmpegVersion
              value: '7'
            - name: nodeName
              value: 'InternalNode'
          ports:
            - name: webui
              containerPort: 8265
            - name: server
              containerPort: 8266
          resources:
            limits:
              gpu.intel.com/i915: '1'
            requests:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /app/configs
            - name: data
              mountPath: /app/server
            - name: logs
              mountPath: /app/logs
            - name: media
              mountPath: /media
            - name: tmp
              mountPath: /temp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - SETUID
                - SETGUID
            readOnlyRootFilesystem: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tdarr-config
        - name: data
          persistentVolumeClaim:
            claimName: tdarr-data
        - name: logs
          persistentVolumeClaim:
            claimName: tdarr-logs
        - name: media
          persistentVolumeClaim:
            claimName: shared-media
        - name: tmp
          emptyDir: {}
