FROM ghcr.io/kagent-dev/kagent/app:0.10.1@sha256:d39d5c948386a4777f4b704cc151bf5bf193ce85c47a8a8e8642644243197f41

USER root

RUN apk update && \
    apk add --no-cache git curl ca-certificates go nodejs

ENV PATH=/usr/local/go/bin:$PATH GOTOOLCHAIN=local

USER 65534:65534
