FROM node:24.20.0-trixie@sha256:f7d34e58713740f9eef9092c0bd6ff10369d132f7238399a4b270f16d47fa608

RUN npm install -g \
      @modelcontextprotocol/server-filesystem@2026.7.10 \
      @cyanheads/git-mcp-server@2.15.1 \
 && npm cache clean --force

RUN <<EOF cat > /etc/gitconfig
[credential]
    helper = store --file=/etc/git-credentials
EOF

USER 65534:65534

WORKDIR /workspace
