FROM moby/buildkit:v0.32.2@sha256:28a898719c18a33f4e8000685287fa36fd0dd9560c6440227d3a732d79bb41d8 AS buildkit

FROM data.forgejo.org/forgejo/runner:13

USER root

RUN apk add --no-cache \
      git \
      bash \
      curl \
      ca-certificates \
      openssh-client \
      tar \
      jq

COPY --from=buildkit /usr/bin/buildctl /usr/local/bin/buildctl

USER 1000
