FROM node:24.19.0-trixie@sha256:e3883d5e4d0b1998cc27f355bd9202cbaf86edc14d07b54b715def0ed4c71093

RUN npm install -g \
      @modelcontextprotocol/server-filesystem@2026.7.10 \
      @cyanheads/git-mcp-server@2.15.1 \
 && npm cache clean --force

RUN <<EOF cat > /etc/gitconfig
[credential]
    helper = store --file=/etc/git-credentials
EOF

USER 65534:65534

WORKDIR /workspace
