FROM moby/buildkit:v0.33.1@sha256:cec9f139f45e93c5c69c60f8b07cfad9f43f4ef6b6a6cd917527fea5ff2e3dea AS buildkit

FROM data.forgejo.org/forgejo/runner:13@sha256:ca3d5eea46004789a175d1369eec6829d3ea9bfbe2011a06625b4bdaa55f7552

USER root

RUN apk add --no-cache \
      git \
      bash \
      curl \
      ca-certificates \
      openssh-client \
      tar \
      jq

COPY --from=buildkit /usr/bin/buildctl /usr/local/bin/buildctl

USER 1000
