FROM python:3.14-slim@sha256:f85c5697265c178cc6887276c55fe16cf3d14ca35c3df6a5eab3b360534a55d2
 
RUN pip install --no-cache-dir \
      "beets[fetchart]==2.14.0" \
      pillow && \
    rm -rf /root/.cache
 
ENV HOME=/config
ENV BEETSDIR=/config
ENV PYTHONDONTWRITEBYTECODE=1
 
USER 65534:65534
 
ENTRYPOINT ["beet"]
