FROM ghcr.io/kagent-dev/kagent/app:0.10.0@sha256:f325bb2db1c3e5b539c4e830a08c4f1b179ed2147468b79efdaee988251c8a44

USER root

RUN apk update && \
    apk add --no-cache git curl ca-certificates go nodejs

ENV PATH=/usr/local/go/bin:$PATH GOTOOLCHAIN=local

USER 65534:65534
