FROM python:3.14-slim@sha256:51dafde81dbdb6ebde285137a295cf18a47ca95234fe388a343719cb97305b3d
 
RUN pip install --no-cache-dir \
      "beets[fetchart]==2.14.0" \
      pillow && \
    rm -rf /root/.cache
 
ENV HOME=/config
ENV BEETSDIR=/config
ENV PYTHONDONTWRITEBYTECODE=1
 
USER 65534:65534
 
ENTRYPOINT ["beet"]
