FROM ghcr.io/kagent-dev/kagent/app:0.9.12@sha256:5ee30b4584e8de3266eb3cc11f5c46e8627716339d04d14166c50bda5f0f4182

USER root

RUN apk update && \
    apk add --no-cache git curl ca-certificates go nodejs

ENV PATH=/usr/local/go/bin:$PATH GOTOOLCHAIN=local

USER 65534:65534
