FROM ghcr.io/kagent-dev/kagent/app:0.10.2@sha256:9eb019e6a0bb5fc1784d3b77025060657153b5cf9b291f63048d9c9f7451435c

USER root

RUN apk update && \
    apk add --no-cache git curl ca-certificates go nodejs

ENV PATH=/usr/local/go/bin:$PATH GOTOOLCHAIN=local

USER 65534:65534
