apiVersion: v1
kind: Service
metadata:
  name: technitium-loadbalancer
  namespace: technitium
  annotations:
    tailscale.com/hostname: dns
    tailscale.com/proxy-group: technitium
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: cluster-tcp
      port: 53443
      targetPort: 53443
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
