apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
  namespace: technitium
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/hetzner-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
