apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium
  namespace: technitium
spec:
  encryptedData:
    DNS_SERVER_ADMIN_PASSWORD: AgBw8DqkveWJ7gnxSSJ9QVS8GgOgKsUpCXSXroKO9yf3tpFQbCcpHyqryDaKg8MUw7f6lDtROkla/9GsYRGmaCI25UhMe6JN4PG4S48TlL4cSgyT3KuaWmbXglBrXei171svdfloIAsTsXV6cv6u6Z7TTwxvte0h9TwsOujrI0AcendrQDXTvRriHTCAGZQCOmTzVooVIT8WOxSJdpQrTE9SlK1njMxjKbuLtkkLO0YfB6aCf0IKcJ1Bb77i7wex5Ee+oBwKTE2m1j/H/2U5BpV8tp7jg+Z3GmZm/zzADjnPXA86OEqssDSqzcF13dA3i3CykgVsKc0obOwaIHRAjfqmdGVyU5UyQfFfjnqeWIPIxnoqj/KjUO5PXr1brlScsAic9UJcwqQGKP6kssNmuvpHGQ8kGQQeuQwOQKg7gCnNYKj63VPyHL66Ls+AkEzUPprq6+V6G1so9BJw5J8+JdSQxn8KIDIZxxbyclvBVv786uLZl0bV9SeEHcno1xdVfGtC0v0gvi3M6V9Fl3Y1W1SUBmg3/eX69MVm0/ID6jmY0yrmu/FyXtTTqkm6C/AodDWaNRAlcBjRon+kHwfpenGITYcDQbGWOVOvu+25NdM3YPtNCOjnM/6tyInFVegcCf2HnkEbkoNOma9wwK0dzteWf6xS0d0eFUbxKZfCCtVT8oDj3jdrpHKIocm+/wGmVJhL7+qa7MswjgMlZBWWGg==
  template:
    metadata:
      name: technitium
      namespace: technitium
