nodes:
  m715q:
    cores: 4
    memory: 32
    ip: 192.168.10.20
    virtualNodes:
      - hostname: m715q-controlplane-1
        type: controlplane
        mainControlplane: true
        cores: 4
        memory: 4
        disk: 100
        ip: 192.168.30.110

      - hostname: m715q-worker-1
        type: worker
        cores: 4
        memory: 20
        disk: 100
        ip: 192.168.30.111
        longhorn:
          enabled: true
          diskSize: 465
          pathInDatastore: '/dev/disk/by-id/ata-Samsung_SSD_870_EVO_500GB_S7EWNL0X362167X' # ls -l /dev/disk/by-id/

  m715q2:
    cores: 4
    memory: 16
    disk: 120
    ip: 192.168.10.21
    virtualNodes:
      - hostname: m715q2-controlplane-1
        type: controlplane
        cores: 4
        memory: 4
        disk: 50
        ip: 192.168.30.120

      - hostname: m715q2-worker-1
        type: worker
        cores: 4
        memory: 8
        disk: 50
        ip: 192.168.30.121
        longhorn:
          enabled: true
          diskSize: 238
          pathInDatastore: '/dev/disk/by-id/ata-Micron_MTFDDAK256TDL_193823DF41CD' # ls -l /dev/disk/by-id/

  m720q:
    cores: 6
    memory: 32
    ip: 192.168.10.22
    virtualNodes:
      - hostname: m720q-controlplane-1
        type: controlplane
        cores: 6
        memory: 4
        disk: 100
        ip: 192.168.30.100

      - hostname: m720q-worker-1
        type: worker
        cores: 6
        memory: 20
        disk: 100
        ip: 192.168.30.101
        longhorn:
          enabled: true
          diskSize: 465
          pathInDatastore: '/dev/disk/by-id/ata-Samsung_SSD_870_EVO_500GB_S6PYNL0Y702707H' # ls -l /dev/disk/by-id/
        igpu:
          enabled: true
          pci_id: '0000:00:02.0'
          pcie: false
          rombar: true

  m920q:
    cores: 6
    memory: 32
    ip: 192.168.10.23
    virtualNodes:
      - hostname: m920q-worker-1
        type: worker
        cores: 6
        memory: 24
        disk: 200
        ip: 192.168.30.131
        longhorn:
          enabled: true
          diskSize: 931
          pathInDatastore: '/dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S75CNS0Y903567P' # ls -l /dev/disk/by-id/
        igpu:
          enabled: true
          pci_id: '0000:00:02.0'
          pcie: false
          rombar: true
