# TODO: don't do this.
#
# kubcetl -n forgejo get svc forgejo-http -o jsonpath='{.spec.clusterIP}' ; echo
#
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: 'forgejo-http.forgejo.svc.cluster.local:3000'
endpoints:
  - url: http://10.106.38.190:3000
