apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-secret
  namespace: semaphore
spec:
  encryptedData:
    secret: AgBmje+b8MtAB48CVOE2ayRY7ryDuhd+9m1nFE4RuHqvRs4JU6hxKeOILoMU8Ab9fiQMV0+7NU/87r7U1VBwak1v3w1AX+vJCLMI8SAE3Ff0VW/A2RTSmvqmJ5f5NI+Ozl1LTxllCUZI5NjNCIpIe2K2zK3aVW3WKLvcT0KGe/Il1E7JQYYnqeF6MhvnmrktYcX3jJIOGDT9+/A/aL7R0k1VJ5X4ci7dFxDGlBayM2oH/+uOEbIkOaO/Cr8FSJfQiOxbIxbZl7G3KrYVNGZZEkzQYNa/f3X1ce3NrCWrTzjF37OSRkfYszm92Pq854i/1fPykomco0iatyIaLWYXvPDeZXcRF0paNb5dSV6X2RSddnt4IW9FP5LwryktG/sHkNB64JmAc3bupcfCASlSCu7gjS2EYYqoqnFAPkkKW4eSuX2zuqRQxN5vPVze5HGjAW4//4UH2Bv+T3bucpOyf25pZ0Z9hytBSZfpx8zeKNZpJxvES1Ut83Ff4hxP+BefxPXaFU+1wYWSKUlu5uxygfoB/RxkLA/qkGaKBh587odEx7ecqsjNwwjQRnkpxMn4AfyjtWI22c2f0SgmaKmwo+Iy9THP+F56tQ0FbbUelH1mkvPo/gxBouon0fHYRx18AgHmvuSwZL8/6mPMWqhrkfkkAzzwargZG/X1YxA73tzSkVEmKPSCzo5Iw0en6ucawxbHBHMteIwBYVE+vh88vkNwxsg0XTd1pf8zHuCkEUQDrZbsFal05q8piUqADMPQ5wGLcNmkQsKhkoxc2U1NlaDyIhBBxQ/tAsiWLbAD/SDGy+0lbxOgF4xhldGDb1+R6cGk1MejgvPIqrxGxcfqVCCURujyIT0llieMGoRPytzucQ==
  template:
    metadata:
      name: authentik-oidc-secret
      namespace: semaphore
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-runner-secret
  namespace: semaphore
spec:
  encryptedData:
    token: AgBx42992rQQu4+qWz3Wygsn+VHRWvdc0H4clZvV+0LcD3HZyPsFCqWSsZfPp6I2F2aY2ObbXg9mo857mWz9XVfVD0oWxO0R6a9smFBJzYLwmqhuVc5WrClQMWC7dK5n9eDQLEEvLRCsTxtT+5H4E5K1PXntpApP4dCnvfh9vBbw1E/dtST1DDJTKjHut2AiyXoP3R/6Zb14YvxXSxtwmMpDpSbw+fmaVrfNL13QsepV8G/5m8MFub98YO85UfB11j2ZtMr+sUqDyFUaudGTew2tUPZ3e8Gl78FHomoR1xgoa19vaDrLnqr5D7YLn/Tw7LBHYJW8zflgMnmh9idESDRrUkko5nEofANnGzJQH3qizud9hc1SYgvwhyEWOP50FSZthkhEqOFBp3a6XB4HtxMbtVv/lCxbBKTspIjhS42nJM7VRiBQADu7uurJz1+AXdmHKB1H7+cyOZjKjHFWnUQVVSJS62B/M0zrPkHSlUbT6x5Jwfa2RaGX9lyOUfrgbeLXVM/SosYP9M9rxAIWAiv2ELgDDXLr9AYPaTdwuR6TqcFpaBYVjrRJqwNaQWuxh3W8Vk/rrAx+lQ9DB2IW03eEMt9KHp6ZrEPo9FqZpg+qkvL77HEAPFRjlOPO1Uz3SEFE3Fr12uJkg8FC3sNZkM+nG0zhbvYpZXrgRvpbjOwUeQqH1fyRYVKke5c8bTwOQn30mZ238C+LcJQuEkSEdKWpKRZas1S6n9B4c+Yas1KsG+gTXWNrh6GgY5o5vXMZdP5kQU8l1ZqJ0QSj8JwvMkX/
  template:
    metadata:
      name: semaphore-runner-secret
      namespace: semaphore
