apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-secret
  namespace: semaphore
spec:
  encryptedData:
    secret: AgBmje+b8MtAB48CVOE2ayRY7ryDuhd+9m1nFE4RuHqvRs4JU6hxKeOILoMU8Ab9fiQMV0+7NU/87r7U1VBwak1v3w1AX+vJCLMI8SAE3Ff0VW/A2RTSmvqmJ5f5NI+Ozl1LTxllCUZI5NjNCIpIe2K2zK3aVW3WKLvcT0KGe/Il1E7JQYYnqeF6MhvnmrktYcX3jJIOGDT9+/A/aL7R0k1VJ5X4ci7dFxDGlBayM2oH/+uOEbIkOaO/Cr8FSJfQiOxbIxbZl7G3KrYVNGZZEkzQYNa/f3X1ce3NrCWrTzjF37OSRkfYszm92Pq854i/1fPykomco0iatyIaLWYXvPDeZXcRF0paNb5dSV6X2RSddnt4IW9FP5LwryktG/sHkNB64JmAc3bupcfCASlSCu7gjS2EYYqoqnFAPkkKW4eSuX2zuqRQxN5vPVze5HGjAW4//4UH2Bv+T3bucpOyf25pZ0Z9hytBSZfpx8zeKNZpJxvES1Ut83Ff4hxP+BefxPXaFU+1wYWSKUlu5uxygfoB/RxkLA/qkGaKBh587odEx7ecqsjNwwjQRnkpxMn4AfyjtWI22c2f0SgmaKmwo+Iy9THP+F56tQ0FbbUelH1mkvPo/gxBouon0fHYRx18AgHmvuSwZL8/6mPMWqhrkfkkAzzwargZG/X1YxA73tzSkVEmKPSCzo5Iw0en6ucawxbHBHMteIwBYVE+vh88vkNwxsg0XTd1pf8zHuCkEUQDrZbsFal05q8piUqADMPQ5wGLcNmkQsKhkoxc2U1NlaDyIhBBxQ/tAsiWLbAD/SDGy+0lbxOgF4xhldGDb1+R6cGk1MejgvPIqrxGxcfqVCCURujyIT0llieMGoRPytzucQ==
  template:
    metadata:
      name: authentik-oidc-secret
      namespace: semaphore
