kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-downloads
  namespace: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-media
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: qbittorrent-media
