ollama:
  ollama:
    mountPath: /data/ollama

    models:
      pull:
        - gemma3:1b
        - gemma3:4b
        - gemma4:e2b
        - gemma4:e4b

  image:
    repository: ollama/ollama
    tag: 0.21.0@sha256:d3d553bdfbcc7f55dd5ddf42c4cbe3a927aa9bb1802710d35e94656ca5aea02b

  extraEnv:
    - name: HOME
      value: /data/ollama
    - name: OLLAMA_MODELS
      value: /data/ollama/models
    - name: OLLAMA_NUM_PARALLEL
      value: '1'
    - name: OLLAMA_MAX_LOADED_MODELS
      value: '1'
    - name: GOMLOCKALL
      value: '1'

  persistentVolume:
    enabled: true
    size: 30Gi

  resources:
    requests:
      cpu: 2
      memory: 6Gi
    limits:
      cpu: 5
      memory: 12Gi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    supplementalGroups:
      - 65534
    seccompProfile:
      type: RuntimeDefault
