ollama:
  ollama:
    mountPath: /data/ollama

    models:
      pull:
        - gemma3:1b
        - gemma3:4b

  image:
    repository: ollama/ollama
    tag: 0.20.3@sha256:87d71eb588a28c747094ca5d011392a3790f6ea9bd9c87594780ad7c65cc7ed1

  extraEnv:
    - name: HOME
      value: /data/ollama
    - name: OLLAMA_MODELS
      value: /data/ollama/models
    - name: OLLAMA_NUM_PARALLEL
      value: '1'
    - name: OLLAMA_MAX_LOADED_MODELS
      value: '1'
    - name: GOMLOCKALL
      value: '1'

  persistentVolume:
    enabled: true
    size: 30Gi

  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    supplementalGroups:
      - 65534
    seccompProfile:
      type: RuntimeDefault
