---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: external-dns
spec:
  encryptedData:
    password: AgBZ0phlmNCSorh9+75jCFxSQH6TmlZdj3XVINKlzipKgrqwePfWmNe1JIjaYFNlZ4ERXoX3dXCsou13XHifQ7X5MAWqUkJFVN5dXw0IuDOxiPTazELfv1n3ATDlemnzDBLvzNuXmf8IjZyfD6BupogtCFxfre9Oi3oswaBWr0GrSZQfnAZZGzqqDFMwO52I/V3Lzu2zONlSzz/NFPTyjGzgs5vDkPKKXhI8zzFg2VW8/5mWKujDuVGwa+LmHmQDVUpXAwUYuCHeiH3EW5yVb54ukawWYFtdp6Xg9/eAzUf1dMDKpnnPFR9KcbX9fMNoxkVCRX6AmQ3WjgcNGtC8WvkjaCYWENh0/r68BKOdYjg2HO9CiXfa0SgUUk0OJu/GxdpiNgEjhxQL6Nj4LU/auH7yA1XYy576eHvJbLG8V8EyK7zxS5ED6W3lTTQApaVQ5N1X4tnwj3AhCycXSEuCYJ66tDAd2CmTRgh+19YLu8FkM59IAVPIHB2s6GpOUgOxFqtgU5qvf1u+u8z1CjXEHU5YQSrGpD7mmvciwzUTqW+gRMzvJuk9eSMBBFDjhTcr4sdhcUMrhDyFq4O+nyNl+tS1PYgNbn5/QceGklSjoxLfsv9YdmCU8zk4G/Wy2ggTf2CRDFN/1p9eWtmuCeNVSwTXJEIJ16+PkwEw1FU6r24xANxTAb/xnHq9cJG+f7LrPORSjUt1x/AsvASgsYCO+1N/n66oI/WToAvuL+8M23ptDg==
  template:
    metadata:
      name: pihole-admin
      namespace: external-dns
