apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: external-dns
spec:
  encryptedData:
    password: AgC8hM0K18mJwBMAchPGTk16zxqQXYlUJCaEtvpWq4yurrtVtIyCcgLEGy+GN5sq8x8DgJ5P9v3bTjT6y72ohRtPOAzyMZcKE0xL38+JBg6J5ZCtIOQu/EdPi2J/pOE9RCxd6b66ilmiOHc2LV7Hq8oitj05uIu6mRHqnWDsRaC1AJiw6HROQ19dGNxp4Nn2/tnfVnWPsFbtqpWJSXmmgnls5ItpMBMacBwrrqnOTgRWWpfWP2m3B1jYSNjyiesucainHi24dCuqKglvWaR3BIopp2pIAbeofSAdU06nAvsZTiqmBMVEYd8wer8ia3YrXCxqxyu+vKHkZvjbZwqH9TAo5eHLq+nG7LzkIlhCRZs+DT/uNyvS6vTJWCzg8fIaE8NQsftfNFzCUTVxOMg1P/fk8/2lM1TiDpYqowkQOM0JrW8oRXfLJO9QEGzK3NyG1nVoLvCkx66UDYSu6AHLnRhueUY5L03SNBGxb3QD4DygTKh+0b/DS9bsjMqlNCunqJB/npfnjIjEK8/2klzjfmflAukMoeOQBXvBh8Z/b8gFHsvP+UB0+UiZd+jsWBeqP84QztIUnAK8wW9myOcAw3M0xigibJU6FQwyQR3H9WfefjEP9ni1ySEW4cEVBBUU/JZXgfVocRHVZ4baDMDYOYuSIzqWLzBzufxUU+IQgNcW0HizzYGy+BJwmm7db74XjTgcgYk82LTjfAwyqMIhSO5IgY0gdLst490SK9rMx7XJMw==
  template:
    metadata:
      name: pihole-admin
      namespace: external-dns
    type: Opaque
