sealed-secrets:
  image:
    registry: docker.io
    repository: bitnami/sealed-secrets-controller
    tag: 0.39.1@sha256:0e5ecab23801caa61b79420488d005377a7264b278c969ee8f78d937daec6931

  containerSecurityContext:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault

  privateKeyLabels:
    bakseter.net/backup: 'true'
