sealed-secrets:
  image:
    registry: docker.io
    repository: bitnami/sealed-secrets-controller
    tag: 0.38.1@sha256:2d18b78e3410c80e6d4163def168a774f36fda74f3b3ea225f0547f99a08e23b

  containerSecurityContext:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault

  privateKeyLabels:
    bakseter.net/backup: 'true'
