sealed-secrets:
  image:
    registry: docker.io
    repository: bitnami/sealed-secrets-controller
    tag: 0.36.0@sha256:a9054cb82fcc54c3cda131e11c6df816531398d1cfd7f36848ce2b6624e90d49

  containerSecurityContext:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
