---
- name: Disable VPN
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - group_vars/all/rb5009.yaml

  module_defaults:
    group/community.routeros.api:
      hostname: "{{ rb5009_host }}"
      username: "{{ rb5009_username }}"
      password: "{{ rb5009_password }}"
      tls: false

  tasks:
    - name: Disable NordVPN peer
      community.routeros.api_find_and_modify:
        path: ip ipsec peer
        find:
          name: NordVPN
        values:
          disabled: true
