---
- name: Enable VPN
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - group_vars/all/hap_ax3.yaml

  module_defaults:
    group/community.routeros.api:
      hostname: "{{ hap_ax3_host }}"
      username: "{{ hap_ax3_username }}"
      password: "{{ hap_ax3_password }}"
      tls: false

  tasks:
    - name: Enable NordVPN peer
      community.routeros.api_find_and_modify:
        path: ip ipsec peer
        find:
          name: NordVPN
        values:
          disabled: false
