apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oidc-secret
  namespace: tailscale
spec:
  encryptedData:
    client-secret: AgBd8GvyZCpCZZAVF/6uNgmZ28OCuaXuXuZJw7gMeYApGFP38oV3Ra0bXdmqPJZQRdoo4j/zfsvg5xE5TuF+NCdWcM2maeZoUMo2E7936m6/u6onwPB3FA8vhiwFMYtEXt1xJGRNo9PK/ONaaY6jgB00AUbQPnpT6fDBks6RfowS2PKBAVG3ZWVsMKylNNmLU7rOlyAz4og+uVIkLQyBrzYe8ukWzkr0au5XZAY5x+KpHbHdhHsGRqgamIvz472h6M7XpoydeMLhm92Z+IpskqZfO6xgNQ3F2hux1qykEuQry5OrXHKLhYkLFhT+lTXyCsv7dmveBUwgNpUvKY4FZklJaIY9Wozq6ZhMQZFAx9k82QGtaxGCtdq44iE98Q7q6HdMcfZ4dUEU7PtvX+wlvqPrNfVdbV+yZNk0OqX3l2QVmHhGcFgXoOV3x4H6ltHVfHUdtOId0PM1ALHqsPZU5py/WMmlQUO103SmFLYR+WwFKRDwIzvRtAcXTDsLbjmkLiDNcyfweiusmX7mjhnCALDCcWwIFS44R7MDgmdDUdlbWHcjJiXhOe7hPuqkcfSBIOAOFFwOrVOEdlxOY0tyTmeZiSnEM0R6GgxKlq7WVWeTGxWeWhXHLD0OAOgG4oBO5kliV95NgQ4FpMdCxshiqvTmzf9GlOhOqI1nxz3rLg9clvk7FLXNubrKh/OO0Kbj3ojOuQuUGjOSPF0xpUyphEuLtg0ZkDG/H2H9A0eJQCXhSsUWt1vViGvY6Nqq9TAopV/c76uN1qBFs5uOHjE5YtptzlqcaF453srgiCgJ2aWncdrmS9jygAfaN1SqIjp0palb40Owyg3U1fpeKdlfrLdplpcJWyc/xYLO5UW9X6w7fg==
  template:
    metadata:
      name: authentik-oidc-secret
      namespace: tailscale
