apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: operator
  namespace: tailscale
spec:
  endpointSelector:
    matchLabels:
      app: operator

  ingress: []

  egress:
    - toEntities:
        - world
        - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ts-ingress
  namespace: tailscale
spec:
  endpointSelector:
    matchLabels:
      tailscale.com/managed: 'true'
      tailscale.com/parent-resource-type: ingress

  ingress: []

  egress:
    - toEntities:
        - world
        - kube-apiserver

    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - rules:
            http: []
          ports:
            - port: '53'
              protocol: TCP
            - port: '53'
              protocol: UDP

    - toEndpoints:
        - matchExpressions:
            - key: 'k8s:io.kubernetes.pod.namespace'
              operator: Exists
