---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAQRPS9qkcYUY9+mVOtsIeaP5Sc2clXQsX8nF2ShHfk1/EHi20cqqWQ9yhsbZlKjJolI744Ak3M4uH8eZpK/uLMIBhVs2d3/w03erG9Kf2orhCMJRQ7dfqxcf0frtz5HmwFUiVSeIp35y4kSvGPHpG0+1wpTjQ0lCvsyBMomrDPC/11BD18AXGZOfzkAL8PuyC9lJhAjF/Eef/Dm40qECrPgCjjhLonPEJVw4X++5JhqR9wHgE7DUJ8e2F3fd0kczahBmnyV8vW0IsCzzf5gO6+VCs4mEC/tKtxNsvFjp7H2HHIk8cf/PwQ2ncEMQVvgzUgBp9LexOrB7gad7MeqzgJ33gNmRLFSw4VxiNp/d4gSJGmtn19np1xlvUCK8QEeHbbQyfRsce1uB5uhsh4tzPAGwS6L0S9yJANS3xFwm0TKUhN5Ib1PU4Pfuiu2kYhl149Db2SetUeEq22UriwQpihKwIIn2z7pkftgO6mj8FSgUmjvapdBo7o7Rud8vXVLZdrDE9nxRdbGK0adAhkPZ2+Wv/PNDQ6UnKmhTOz8YM/8IzVPQ2JE5friVvh1RvpWvcyTqnYTvKaEmsuac9zaLTesnLe6QuWY3gW3Csha70b/RPszd9CnWSlxMfics6C+pNgYjd2EYQ//vSjseeTUafkWBwNfR9MZLdRnCxgiOvXYQzKYZO8qQ7K1BRlagVZNAkLbtYBbN8pVYkRZliHV+yUlw==
    client_secret: AgAQlu17t2IVaS0IToRbii6M0NvPHNMaLAIAKlqOCf8wbWIpN0mLo7FdLCdU2xmf48UauJqfEo/sjTIqnvzSl2GIK/blWZgSmwdIb3NQEOtrZkgOQRy3oqApXz8KzvIQXkeYsPkgp+0s/kCryKVZa3moASjD0MKidXaiBXhuwhIZyzRLTD3zJyw4hbXFi2ehUZAHATe9VvRzTPH1lfArf3TjSDySpArns/CLph/h/yGLyXXYn3MiNlSGuoYTcV1NgDg+zqoBXO2l8h/y3GY7WoAiW0BxEJhHjIOa/GKY1/77K4wbmGcdvlV2Hmg/UwURq+6ouKNn/Nq5PtZm5Iu6i8OtuB2KNvmghEW3eYWfB5o5nWW+9UyeHIgDoorgx/yxShFrIzUEJDY2ao3B1ssnaFXTyHZEYX4TdbXFph6LqccdwuhWDADrG+Sk9NJSYLDlhYX8J9CZ3zRoimYfMsT1j/uwAffJ+tXv1JsCwSg5gtj9iMzGNB/6OFCNpZQGw8/6jmGOhoCXWmxrHWzhrdpzuZH8G+85a9RMr7xEahGfs+15psN+jNnc3H+JZ7p/k1Sc+TfqQkcSCc77lnxTAfzZP0lSHy+2U3Q/GJw+QdmdniLayI3/0iG2jpgLFe59BmGjcsxmeDhYn7i0KiaUs0M3+MyWSvLLHUZ5xTMb1G0x4GD31fqQMX5IXsRdTxBAL2VEn+7Gh/enHV0mb7G7/smWPlEx8xgjMvOCP/wK1+2VYqi7mq9Tusqq2gk+S1uKxLpHQa8OyEXw+QcU5mntVf5ruVg=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
