apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: homelab
  namespace: tailscale
spec:
  type: kube-apiserver
  replicas: 2
  tags: ['tag:k8s']
  kubeAPIServer:
    mode: auth
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress
  namespace: tailscale
spec:
  type: ingress
  replicas: 2
  tags: ['tag:k8s']
