apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authentik-forward-auth-sre
  namespace: tailscale
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: bakseter-net-gateway-sre
  extAuth:
    failOpen: false
    timeout: 30s
    http:
      backendRefs:
        - name: ak-outpost-envoy-gateway-sre
          namespace: authentik
          port: 9000
      headersToExtAuth:
        - cookie
        - authorization
        - x-forwarded-for
        - x-forwarded-host
        - x-forwarded-proto
      path: /outpost.goauthentik.io/auth/nginx
