cert-manager:
  replicaCount: 2

  image:
    repository: quay.io/jetstack/cert-manager-controller
    tag: v1.21.1@sha256:416a2d76870d996460e62bd7f521bf14fa017be9e3e904aab92163a331fcb61a

  webhook:
    replicaCount: 2

    image:
      repository: quay.io/jetstack/cert-manager-webhook
      tag: v1.21.1@sha256:d8b3961b51c8c7320633f8208dc46bf88aa13804d0f7cbe48a096b2c523cee42

  cainjector:
    enabled: true
    replicaCount: 2

    image:
      repository: quay.io/jetstack/cert-manager-cainjector
      tag: v1.21.1@sha256:7c65d8478484155f6f1886b1ed60064e854c7c371b1fddbe220c71e5574e6526

  crds:
    enabled: true

  config:
    enableGatewayAPI: true

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

  # bakseter.net is hosted on Cloudflare
  dns01RecursiveNameservers: '1.1.1.1:53'
  dns01RecursiveNameserversOnly: true
