cert-manager:
  crds:
    enabled: true

  config:
    enableGatewayAPI: true

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

  # bakseter.net is hosted on Cloudflare
  dns01RecursiveNameservers: 1.1.1.1
  dns01RecursiveNameserversOnly: true
