traefik:
  service:
    spec:
      type: ClusterIP

  deployment:
    replicas: 3

  providers:
    kubernetesCRD:
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
    kubernetesGateway:
      enabled: true

  gateway:
    listeners:
      public:
        port: 9000
        protocol: HTTP
        namespacePolicy:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - authentik
                  - bakseter-net
                  - mandagsmiddag

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi

  ports:
    # Disable default entrypoints
    web:
      expose:
        default: false
    websecure:
      expose:
        default: false
    traefik:
      expose:
        default: false

    public: # Cloudflare Tunnel
      expose:
        default: true
      port: 9000
      exposedPort: 9000
      forwardedHeaders:
        trustedIPs:
          - '10.244.0.0/16' # trusts internal pod network

  api:
    dashboard: false

  additionalArguments:
    - '--serversTransport.insecureSkipVerify=true'

  logs:
    access:
      enabled: true

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
          topologyKey: bakseter.net/physical-node
