traefik:
  image:
    registry: docker.io
    repository: traefik
    tag: v3.7.3
    # takes precedence over tag
    digest: sha256:6b9cbca6fac42ab0075f5437d8dc1685cfd188626d8d515839ea94f8b6271c42

  service:
    spec:
      type: ClusterIP

  deployment:
    replicas: 2

  providers:
    kubernetesCRD:
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
    kubernetesGateway:
      enabled: true

  gateway:
    listeners:
      public:
        port: 9000
        protocol: HTTP
        namespacePolicy:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - authentik
                  - bakseter-net
                  - mandagsmiddag

  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi

  ports:
    # Disable default entrypoints
    web:
      expose:
        default: false
    websecure:
      expose:
        default: false
    traefik:
      expose:
        default: false

    # Cloudflare tunnel
    public:
      expose:
        default: true
      port: 9000
      exposedPort: 9000
      forwardedHeaders:
        trustedIPs:
          # Trusts internal pod CIDR. In practice only cloudflared b/c networkpolicy.
          - '10.244.0.0/16'

  api:
    dashboard: false

  additionalArguments:
    - '--serversTransport.insecureSkipVerify=true'

  logs:
    access:
      enabled: true
      format: json
      fields:
        headers:
          defaultMode: keep

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
          topologyKey: bakseter.net/physical-node
