grafana-operator:
  image:
    registry: ghcr.io
    repository: grafana/grafana-operator
    tag: v5.24.0@sha256:e72d11ac579a000fe0ddcc0c3341a5103a1c93a28fbc394dc7c7009ed071d1a7

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
