apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rustfs
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: rustfs

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: index-gateway
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-scheduler
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '9000'
              protocol: TCP

  egress: []
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-query-frontend
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: query-frontend

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP
            - port: '39202'
              protocol: TCP
            - port: '51326'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-scheduler
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: loki
            app.kubernetes.io/name: rustfs
      toPorts:
        - ports:
            - port: '9000'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-querier
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: querier

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
      toPorts:
        - ports:
            - port: '3100'

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP
            - port: '39202'
              protocol: TCP
            - port: '51326'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP
            - port: '9095'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: index-gateway
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-scheduler
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: loki
            app.kubernetes.io/name: rustfs
      toPorts:
        - ports:
            - port: '9000'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-canary
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: canary

  ingress: []

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-gateway
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: gateway

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alloy
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: canary
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app: grafana
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-ingester
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: ingester

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: alloy
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP
            - port: '9095'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: canary
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP
            - port: '9095'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP
            - port: '9095'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP
            - port: '7946'
              protocol: TCP
            - port: '40658'
              protocol: TCP
            - port: '47376'
              protocol: TCP
            - port: '60030'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: loki
            app.kubernetes.io/name: rustfs
      toPorts:
        - ports:
            - port: '9000'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-distributor
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: distributor

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP
            - port: '7946'
              protocol: TCP
            - port: '40658'
              protocol: TCP
            - port: '47376'
              protocol: TCP
            - port: '60030'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: '3100'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: compactor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP
            - port: '9095'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: loki
            app.kubernetes.io/name: rustfs
      toPorts:
        - ports:
            - port: '9000'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-compactor
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: compactor

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP
            - port: '9095'
              protocol: TCP

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: distributor
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: ingester
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '7946'
              protocol: TCP

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: loki
            app.kubernetes.io/name: rustfs
      toPorts:
        - ports:
            - port: '9000'
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-query-scheduler
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: query-scheduler

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: query-frontend
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP

  egress: []
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: loki-index-gateway
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: index-gateway

  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: querier
      toPorts:
        - ports:
            - port: '9095'
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: loki
            app.kubernetes.io/name: rustfs
      toPorts:
        - ports:
            - port: '9000'
              protocol: ANY
