keel:
  image:
    tag: 0.21.1@sha256:a6a7ab0785989ecb43b6e2810ef225656a59eaf5dd6e8c65c37b16ebc9974c60

  helmProvider:
    enabled: false

  secret:
    enabled: false

  podSecurityContext:
    runAsUser: 666 # matches the UID inside the container
    runAsGroup: 666 # matches the GID inside the container
    fsGroup: 666 # matches the GID inside the container
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
