longhorn:
  preUpgradeChecker:
    jobEnabled: false

  defaultSettings:
    defaultDataPath: /var/lib/longhorn
    createDefaultDiskLabeledNodes: true
    replicaAutoBalance: best-effort
    snapshotDataIntegrity: disabled
    storageReservedPercentageForDefaultDisk: 20

  defaultBackupStore:
    backupTarget: s3://bakseter-homelab-longhorn@hel1/
    backupTargetCredentialSecret: longhorn-backup-secret
    pollInterval: 600

  persistence:
    defaultClassReplicaCount: 3

  networkPolicies:
    enabled: true

  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

  httproute:
    enabled: true

    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: int-bakseter-net
        namespace: tailscale

    hostnames:
      - longhorn.int.bakseter.net
