apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-sso-secret
  namespace: vaultwarden
spec:
  encryptedData:
    SSO_CLIENT_SECRET: AgB0xerV+ptWv+plSY84tEnZBMhP3Cjupg1Pud0ZkVaPtXQHl2dwTQq4DiQBQdv7rkzBGCcR0FOn0UbbxzR8U8ZRHg4JcGECgndiKDWHZl9BMs3JpbI3gOV6IQ3g4zW2y2ngiAB7FqIDP/vxEPD9uRAQQTdv9Z+pAeXNVwp7zRBOLm5ztujSOouEYE9lTXodfYacNAdW1HddSLKwZ/Lk18toSdzmWoZAwUMjS5V9ecLle/VWyRG6up1s0fefT+3NLzPCP+cLDtoUYc9Y2crgnxEi470PKkGPXnz7BKbBsgxB5a+/gmx95J9RZQifcsaxt4IR0PJg3Lk9FMqrGd48GxErqDl6Whx4E3r3O4PBL0KCIyLeVVHarpMw108C+w+NE++m0qweEyMvGNokbPRMcPZuCunR643A/BJ0QrMKktT2E3ug1FpJ6KvqOkyxG8tljykKywMzD3r9dLAvwkdaz/q7q6MErkPR0oRdbUYxiM8yBaFLr95lV9iKk2cOlLAKaxV3gtWm42XQRhJ2DA3kFlL7cqE510wL5HMVBRcJT/XRGhIOTRDv8MQ28z7w8HpHXrDXF4wLEADZ2YddKLs8wDqX6RWkxxq7HhYGiw/sH9Eitnl2qBQl+nwfaLqE6WLhQyI/IyNgmKq/oxZtMj6oSZHa/+1rpxV3XxYboMVoTiN4hnLQpUZfycYmbhpErpVW9Ju+3Y/P0Nn+aMS2dnCQUejMNoPttpJJrERiBGYSfLAH7Ax3EDmL64p1V2SKofFM1H1XJ02KxK1g70ijNzXRnh9Gf+zLx1j+A2tr58cE8ekfRPm0zAfPKTS13dL+1JNF4XLVv2Nz1nVZgQRJfhSL9k5p7Jq7miYOWq90Y88Thz6U1A==
  template:
    metadata:
      name: vaultwarden-sso-secret
      namespace: vaultwarden
