cilium:
  ipam:
    mode: kubernetes

  kubeProxyReplacement: true

  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

  cgroup:
    autoMount:
      enabled: false

    hostRoot: /sys/fs/cgroup

  k8sServicePort: 7445

  socketLB:
    hostNamespaceOnly: true

  ### END talos

  l2announcements:
    enabled: true

  lbIPAM:
    enabled: true

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

  dashboards:
    enabled: true
    namespace: monitoring

  operator:
    dashboards:
      enabled: true
      namespace: monitoring

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack

  hubble:
    relay:
      enabled: true

      prometheus:
        enabled: true

        serviceMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack

    ui:
      enabled: true

    metrics:
      enableOpenMetrics: true

      dynamic:
        enabled: true

        config:
          content:
            - name: dns
              contextOptions:
                - name: query # adds the queried domain as a label
                - name: ignoreAAAA # drops AAAA queries to reduce cardinality
                - name: sourceContext
                  values:
                    - workload-name
                    - reserved-identity
                - name: destinationContext
                  values:
                    - workload-name
                    - reserved-identity

            - name: flow
              contextOptions:
                - name: sourceContext
                  values:
                    - workload-name
                    - reserved-identity
                - name: destinationContext
                  values:
                    - workload-name
                    - reserved-identity

            - name: drop
              contextOptions:
                - name: any-drop # counts ALL drop reasons, not just policy-denied
                - name: sourceContext
                  values:
                    - workload-name
                    - reserved-identity
                - name: destinationContext
                  values:
                    - workload-name
                    - reserved-identity

            - name: tcp
              contextOptions:
                - name: sourceContext
                  values:
                    - workload-name
                    - reserved-identity
                - name: destinationContext
                  values:
                    - workload-name
                    - reserved-identity

            - name: icmp
              contextOptions:
                - name: sourceContext
                  values:
                    - workload-name
                    - reserved-identity
                - name: destinationContext
                  values:
                    - workload-name
                    - reserved-identity

            - name: httpV2
              contextOptions:
                - name: exemplars
                  values:
                    - true
                - name: labelsContext
                  values:
                    - source_ip
                    - source_namespace
                    - source_workload
                    - destination_ip
                    - destination_namespace
                    - destination_workload
                    - traffic_direction
                - name: sourceContext
                  values:
                    - workload-name
                    - reserved-identity
                - name: destinationContext
                  values:
                    - workload-name
                    - reserved-identity

            - name: port-distribution

            - name: policy
              contextOptions:
                - name: sourceContext
                  values:
                    - app
                    - workload-name
                    - pod
                    - reserved-identity
                - name: destinationContext
                  values:
                    - app
                    - workload-name
                    - pod
                    - dns
                    - reserved-identity
                - name: labelsContext
                  values:
                    - source_namespace
                    - destination_namespace
              excludeFilters:
                - destination_pod:
                    - default/

      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack

      dashboards:
        enabled: true
        namespace: monitoring
