apiVersion: v2
name: intel-device-plugins-operator-umbrella
version: 0.1.0
dependencies:
  - name: intel-device-plugins-operator
    version: 0.36.0
    repository: https://intel.github.io/helm-charts
