kagent:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  providers:
    default: openAI
    openAI:
      model: mistral-medium-3-5

  controller:
    agentImage:
      registry: ghcr.io
      repository: bakseter/homelab/ghcr.io/kagent-dev/kagent/app
      tag: 0.10.0-rc2@sha256:c85838551cf37115840c3d23591aeebcff42a8b3966f75787d5ab75d896928ea

  ui:
    httpRoute:
      enabled: true

      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: tailscale-int
          namespace: tailscale

      hostnames:
        - kagent.int.bakseter.net

      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /

  argo-rollouts-agent:
    enabled: false
  cilium-debug-agent:
    enabled: false
  cilium-manager-agent:
    enabled: false
  cilium-policy-agent:
    enabled: false
  helm-agent:
    enabled: false
  istio-agent:
    enabled: false
  k8s-agent:
    enabled: false
  kgateway-agent:
    enabled: false
  observability-agent:
    enabled: false
  promql-agent:
    enabled: false
  grafana-mcp:
    enabled: false
  querydoc:
    enabled: false
