name: Sync Tailscale ACLs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get policy file from GitHub Secrets
        run: echo "$TS_POLICY_FILE" > policy.hujson
        env:
          TS_POLICY_FILE: ${{ secrets.TS_POLICY_FILE }}

      - name: Deploy ACL
        if: ${{ github.event_name == 'push' }}
        uses: tailscale/gitops-acl-action@4105afd651aa659e0eec9031a10360c39fbc0804 # v1.5.1
        with:
          action: 'apply'
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}

      - name: Test ACL
        if: ${{ github.event_name == 'pull_request' }}
        uses: tailscale/gitops-acl-action@4105afd651aa659e0eec9031a10360c39fbc0804 # v1.5.1
        with:
          action: 'test'
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailnet: ${{ secrets.TS_TAILNET }}
