prometheus-blackbox-exporter:
  image:
    registry: quay.io
    repository: prometheus/blackbox-exporter
    tag: v0.29.0@sha256:9613f2884689b6fad9f1939f6a3b0388c93a022cfaededb19545b329b5c83dea

  releaseLabel: true

  serviceMonitor:
    enabled: true
    defaults:
      interval: 60s
    labels:
      release: kube-prometheus-stack

    selfMonitor:
      enabled: true
      interval: 60s
      labels:
        release: kube-prometheus-stack
