prometheus-blackbox-exporter:
  releaseLabel: true

  serviceMonitor:
    enabled: true
    defaults:
      interval: 60s

    selfMonitor:
      enabled: true
      interval: 60s

    targets:
      - name: authentik
        url: https://authentik.bakseter.net
        hostname: authentik.bakseter.net

      - name: bakseter-net
        url: https://bakseter.net
        hostname: bakseter.net

      - name: mandagsmiddag.no
        url: https://mandagsmiddag.no
        hostname: mandagsmiddag.no
