apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-database
  namespace: vaultwarden
  labels:
    bakseter.net/backup-primary: 'true'
spec:
  instances: 1
  storage:
    size: 2Gi
