podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  supplementalGroups:
    - 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

domain: https://vaultwarden.bakseter.no

strategy:
  type: Recreate

image:
  registry: docker.io
  repository: vaultwarden/server
  tag: 1.37.2-alpine@sha256:d16a304c2476fd787634ddde2c00be8fdfa1a72539438c626ece3686b5b88ab4

storage:
  data:
    name: vaultwarden-data
    size: 1Gi
    class: longhorn-encrypted
    path: /data
    accessMode: ReadWriteOnce

  attachments:
    name: vaultwarden-files
    size: 1Gi
    class: longhorn-encrypted
    path: /files
    accessMode: ReadWriteOnce

database:
  type: postgresql
  existingSecret: vaultwarden-database-app
  existingSecretKey: uri

sso:
  enabled: false
