podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  supplementalGroups:
    - 1000
  seccompProfile:
    type: RuntimeDefault

replicas: 1

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

domain: https://vaultwarden.bakseter.no

strategy:
  type: Recreate

image:
  registry: docker.io
  repository: vaultwarden/server
  tag: 1.37.3-alpine@sha256:9a905c5cf5df61bb827da3805e160170741c0b53b0c63bb07e1afd3d2e21b1c8

storage:
  data:
    name: vaultwarden-data
    size: 1Gi
    class: longhorn-encrypted
    path: /data
    accessMode: ReadWriteOnce

  attachments:
    name: vaultwarden-files
    size: 1Gi
    class: longhorn-encrypted
    path: /files
    accessMode: ReadWriteOnce

database:
  type: postgresql
  existingSecret: vaultwarden-database-app
  existingSecretKey: uri

sso:
  enabled: false
