vaultwarden:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    supplementalGroups:
      - 1000
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  domain: https://vaultwarden.tail79d70a.ts.net

  image:
    registry: docker.io
    repository: vaultwarden/server
    tag: 1.35.7-alpine@sha256:9a54dad95452412afb959664dc5d6c3c3ca7c4131116ca7667888b0376320b03

  ingress:
    enabled: true

    class: tailscale
    hostname: vaultwarden

  database:
    type: postgresql
    existingSecret: vaultwarden-database-app
    existingSecretKey: uri

  replicas: 0 # TODO: remove
